/// Combined 3-DOF Motion + Laser  -  GENERATED FILE, DO NOT EDIT BY HAND
/*
  Generated by python/scripts/build_merged_firmware.py from:
    3DOF_MovementF/3DOF_MovementF.ino
    shootingyesready_inoF-1/shootingyesready_inoF-1.ino

  Edit those two files and re-run the build script. Editing this file directly
  means the next build silently discards your change.

  WHY THIS EXISTS
    Both sketches are needed at once on a single Teensy 4.1. Their pins do not
    collide (motion uses 0-7, 16, 17, 20, 21; the laser relays use 8, 9, 10) and
    the only clashing symbols are setup() and loop(). This file renames those
    two per sketch and adds a dispatcher; everything else is carried over
    unchanged.

  COMMAND DISPATCH
    Three numbers        linear_mm_relative rotation_deg_relative flexion_deg_absolute
    home | h             return all three axes to the home state
    e r f p s x          laser: enable, ready, fire, pause, standby, stop
    1 2 3 4 o g t y w ?  laser: channel, polarity, order, gap, bench test, status
    q                    toggle terse output / host mode
    v<us>                set the STEP pulse half-period, 40-5000 us

    The two alphabets do not overlap, so routing is unambiguous.

  TERSE MODE IS HOST MODE
    Send [q] once after connecting. It does two things, both of which matter
    only when a program is driving:

      1. Drops the verbose prints. At ~20 commands/s the pre-move report and
         full summary are ~900 bytes per command -- about 80 ms of transmission
         at 115200, more than the motion itself takes.
      2. Makes flexion fire-and-forget. Re-commanding an absolute servo target
         20x a second restarts its acceleration ramp before it reaches speed,
         which is what makes flexion click rather than move.

    The line the host synchronises on is still printed. Terse resets on boot.

  WHY A JOG USED TO BARELY MOVE
    runSimultaneousMovementLoop() runs while ANY axis is unfinished, and flexion
    counted as unfinished whenever the servo was connected -- even when the
    command was not asking it to move. So every linear-only jog waited on the
    servo: 40 ms for a feedback poll, or the full 500 ms no-change timeout if
    the servo sat a couple of steps off target. Combined with the print cost,
    the linear axis was stepping about a quarter of the time. Both are fixed
    here: an unchanged flexion target now completes immediately.

  !!! LIVE FAIL-SAFE HAZARD - READ BEFORE POWERING OR FLASHING !!!
    READY_ON_NC is true, so pin 8 is on the relay's NC terminal. That makes the
    ready contact CLOSED - the laser ARMED - whenever the coil is de-energised:

      pin 8 LOW  / coil released   -> contact CLOSED -> ARMED
      pin 8 HIGH / coil energised  -> contact OPEN   -> standby

    Standby therefore depends on the coil staying energised. A Teensy reset, a
    USB replug, a firmware upload, a loose jumper, or loss of the relay supply
    all release the coil and ARM THE LASER with nobody commanding it. Flashing
    this file does exactly that for the duration of the upload.

    Before flashing, de-energise the relay supply. Do not leave the rig
    energised unattended.

    The real fix is hardware: move the pin 8 wire from the relay's NC terminal
    to its NO terminal, then set READY_ON_NC = false in the source sketch and
    regenerate. That makes de-energised mean standby, and power loss fail safe.

    (Comments in the source sketch claim pin 8 was moved to NO. They are stale.
    The value of READY_ON_NC is what this build follows.)

  WHAT THE SOFTWARE ALREADY DOES ABOUT IT
    setupLaserOutputs() writes the safe level BEFORE pinMode(), so pin 8 drives
    standby the instant it becomes an output rather than glitching through
    armed first. setup() calls laserSetup() before motionSetup() so that
    happens as early as possible. This closes the reset-to-setup window; it
    cannot close the window while the Teensy is held in reset or being
    programmed, because the pin is not an output then. That window is hardware.

  A LIMITATION WORTH KNOWING
    A motion command blocks until the move finishes, so a laser command sent
    during a move waits for it. Keep per-command moves short (the host caps them
    in system.yaml) to bound that wait.
*/

// Terse mode is really "host mode": it suppresses the chatty prints AND stops
// the movement loop waiting for the servo to arrive. Both are right when a
// program is issuing ~20 commands a second and wrong when a human is typing.
// Toggled at runtime with [q]; off at boot so the Serial Monitor stays usable.
bool terseOutput = false;

// Last flexion target actually sent to the ST3020. A jog that only moves the
// linear or rotation axis re-sends the same flexion target every command; without
// this the movement loop would wait for the servo on every one of them.
int lastCommandedFlexionSteps = 2048;   // flexionNeutralStep, commanded in setup()


// =========================================================================
// Motion sketch, from 3DOF_MovementF.ino
// =========================================================================


///------------------------------------------------ ST3020 Setup ---------------------------------------------------

// Include the library used to communicate with the ST3020
#include <SCServo.h>

// Include math functions such as fabsf, lroundf, and isfinite
#include <math.h>

// Create the ST3020 communication object
SMS_STS servo;

///------------------------------------------------ Pin Assignments ------------------------------------------------

// Linear Axis using NEMA 14 and TB6600
const int linear_enaPin = 2;   // Pin 2 sends enable control to the linear TB6600 driver ENA input
const int linear_dirPin = 3;   // Pin 3 sends direction control to the linear TB6600 driver DIR input
const int linear_stepPin = 4;  // Pin 4 sends step pulses to the linear TB6600 driver PUL or STEP input

// Linear Motor Encoder Channels
const int linear_encA = 17;  // Pin 17 reads linear encoder channel A
const int linear_encB = 16;  // Pin 16 reads linear encoder channel B

// Rotation Axis using NEMA 17 and TB6600
const int rotation_enaPin = 5;   // Pin 5 sends enable control to the rotation TB6600 driver ENA input
const int rotation_dirPin = 6;   // Pin 6 sends direction control to the rotation TB6600 driver DIR input
const int rotation_stepPin = 7;  // Pin 7 sends step pulses to the rotation TB6600 driver PUL or STEP input

// Rotation Motor Encoder Channels
const int rotation_encA = 20;  // Pin 20 reads rotation encoder channel A
const int rotation_encB = 21;  // Pin 21 reads rotation encoder channel B

// ST3020 and Waveshare Bus Servo Adapter Communication Pins Documentation
// Serial1 automatically uses pins 0 and 1 on Teensy 4.1
// const int servo_rxPin = 0; // Pin 0 is Teensy RX1
// const int servo_txPin = 1; // Pin 1 is Teensy TX1

///--------------------------------------------- Electrical Settings ----------------------------------------------

// Enabled / Disabled Settings
// LOW enables the TB6600 driver with this wiring
// HIGH disables the TB6600 driver with this wiring
const int enaPin_Enable = LOW;
const int enaPin_Disable = HIGH;

// Direction Levels for the Linear Axis
const int linear_dirForward = LOW;    // was HIGH
const int linear_dirBackward = HIGH;  // was LOW

// Direction Levels for the Rotation Axis
const int rotation_dirClockwise = HIGH;   // flipped from LOW to reverse rotation direction
const int rotation_dirCounter = LOW;      // flipped from HIGH to reverse rotation direction

// Common conversion numbers written as named constants so the math is easier to read
const int degreesPerRevolution = 360;
const int halfRevolutionDegrees = 180;
const int servoMaximumStep = 4095;

// Status printing interval during movement
const unsigned long printInterval_ms = 40;

///---------------------------------------------- Linear Settings -------------------------------------------------

// TR8x4 Lead Screw moves 4 mm during 1 motor revolution
const float linearMMPerRev = 4.0;

// Number of STEP pulses required for 1 motor revolution
// Change this value to match the TB6600 microstep setting
const float linearPulsesPerRev = 1600.0;

// Encoder counts per motor revolution when using 1x decoding on Channel A
const float linearEncoderCPR = 1000.0;

// Stop when the measured linear motion is this close to the requested motion
// 0.005 mm is approximately 1 encoder count because 4 mm / 1000 counts = 0.004 mm per count
const float linearStopMarginMM = 0.005;

// Absolute TR8x4 lead screw travel range
const float linearMinPositionMM = 0.0;
const float linearMaxPositionMM = 177.0;

// Small tolerance used only to avoid rejecting tiny floating-point roundoff near 0 or 177
// 0.01 mm is approximately 2.5 encoder counts at the boundary because 0.01 / 0.004 = 2.5
const float linearRangeToleranceMM = 0.01;

// Change this value to +1 or -1 if the displayed encoder direction is reversed
// If absolute position decreases during a positive linear move, change this sign
const int linearEncoderSign = -1;   // was +1

// volatile means this variable can change inside an interrupt at any time
volatile long linearEncoderCount = 0;

// This variable stores the tracked absolute linear position of the TR8x4 lead screw
// The code starts this at 0 mm during setup, so the hardware must physically begin at 0 mm
float currentLinearPositionMM = 0.0;

// Estimated linear movement for one pulse = 4 / 1600 = 0.0025 mm

///--------------------------------------------- Rotation Settings ------------------------------------------------

// Number of encoder counts for 1 motor revolution when using 1x decoding
const float rotationEncoderCPR = 1000.0;

// Number of STEP pulses required for 1 rotation motor revolution
// This is used for printing and for a backup stop if encoder feedback fails
const float rotationPulsesPerRev = 1600.0;

// Motor rotates 2.5 degrees for every 1 degree of ureteroscope rotation
const float rotationGearRatio = 2.5;

// Stop when the motor encoder is within this many motor degrees of the target
// 0.18 motor degrees is approximately half an encoder count because 360 / 1000 = 0.36 motor degrees per count
// Through the 2.5 to 1 gear ratio, 0.18 motor degrees is about 0.072 ureteroscope degrees
const float rotationStopMarginMotorDeg = 0.18;

// Change this value to +1 or -1 if the displayed encoder direction is reversed
const int rotationEncoderSign = +1;

// volatile allows the interrupt routine to update this value at any time
volatile long rotationEncoderCount = 0;

// This variable stores the mapped absolute rotation position of the ureteroscope
// The code starts this at 0 degrees during setup, so the ureteroscope must physically begin flat
// The map wraps full revolutions so +360 degrees and -360 degrees become 0 degrees again
float currentRotationMapDeg = 0.0;

// Small tolerance used to clean the rotation map back to 0 near a full revolution
const float rotationMapZeroToleranceDeg = 0.5;

///---------------------------------------------- Flexion Settings ------------------------------------------------

// ST3020 Communication and Movement Settings
const long servo_baud = 1000000;
const int servo_ID = 1;
const int servo_speed = 500;         // Slow steady movement
const int servo_acceleration = 100;  // Soft ramp-up profile

// Flexion Speed Reduction Settings
// The ST3020 uses a larger speed command for faster movement and a smaller speed command for slower movement
// The target tip angle is used as a precautionary speed limit for each flexion command
// Targets from -100 to +100 tip degrees use the normal servo_speed of 500
const int flexionSlowdownStartTipDeg = 100;

// Above 100 tip degrees subtract 2.5 speed units for every additional tip degree
// Examples with a normal speed of 500:
// 150 tip degrees gives 500 - (50 * 2.5) = 375
// 200 tip degrees gives 500 - (100 * 2.5) = 250
// 250 tip degrees gives 500 - (150 * 2.5) = 125
const float flexionSpeedReductionPerTipDeg = 2.5;

// Do not allow the calculated speed command to fall below this value
const int flexionMinimumSpeed = 50;

// Flexion Overstretch Warning Levels use the absolute target angle
// This means the same warning is printed for positive and negative flexion
const int flexionSmallWarningTipDeg = 150;
const int flexionModerateWarningTipDeg = 200;
const int flexionMajorWarningTipDeg = 250;

// ST3020 Center Position used as 0 deg Base Motor Angle and 0 deg Base Tip Flexion
const int flexionNeutralStep = 2048;

// Servo Target Tolerance in encoder steps
// 1 ST3020 step is about 0.088 motor degrees because 360 / 4095 = 0.088
// Tip degrees per ST3020 step depend on the selected calibration range
const int flexionStopMarginSteps = 8;   // ~0.7 motor deg; 1 was unreachable under load

///---------------------------------------------- FLEXION CALIBRATION --------------------------------------------
// Positive and negative targets use the same ranges:
//   0 through 90 degrees       uses 6.0
//   over 90 through 180        uses 6.5
//   over 180 through 270       uses 7.2
const float flexionTwistFactor0To90 = 6.0;
const float flexionTwistFactor90To180 = 6.5;
const float flexionTwistFactor180To270 = 7.2;

const float flexionGearRatio = 3.5;

// Flexion Max and Min 360 Servo Movement
// Counts = encoder counts
// Steps = physical steps
// Neutral: 0 degrees = 2048 counts/steps
// The ST3020 conversion represents -180 through +180 motor degrees around neutral
const float flexionMaxMotorDeg = 180.0;
const float flexionMinMotorDeg = -180.0;

// The allowed absolute ureteroscope tip range is -270 through +270 degrees
const float flexionMaxTipDeg = 270.0;
const float flexionMinTipDeg = -270.0;

// Flexion range tolerance equivalent to one ST3020 encoder count
// 1 count is about 0.088 motor degrees because 360 / 4095 = 0.088
const float flexionRangeToleranceMotorDeg = degreesPerRevolution / (float)servoMaximumStep;
const float flexionRangeToleranceTipDeg =
  flexionRangeToleranceMotorDeg * (flexionTwistFactor180To270 / flexionGearRatio);

// Stop waiting if the ST3020 encoder has not changed for this long
// This prevents endless printing when the servo reaches a mechanical limit before the exact target
const unsigned long flexionNoChangeTimeout_ms = 500;

///----------------------------------------------- Motion Timing --------------------------------------------------

// STEP signal stays HIGH for 800 us and LOW for 800 us
// One pulse takes 1600 us which is approximately 625 pulses per second
unsigned int stepDelay_us = 800;   // runtime-settable with [v<us>]

// Short wait after setting direction and before sending the first STEP pulse
const unsigned int directionSetup_us = 10;

///------------------------------------------------ Input Variables ------------------------------------------------

// True once ST3020 responds during startup diagnostics
bool servoConnected = false;

// These three variables store the one-line user command
// Example input "4 90 20" means +4 mm relative linear movement,
// +90 degrees relative rotation, and an absolute +20-degree flexion target
float requestedLinearMM = 0.0;
float requestedRotationDeg = 0.0;
float requestedFlexionDeg = 0.0;

// True only when the user types the explicit home command or h shortcut
// In that case the code calculates the relative movement needed to return to home state
bool homeCommandRequested = false;

///----------------------------------------------- Linear Target State --------------------------------------------

// Linear input is relative movement from the current absolute position
float targetLinearRelativeMM = 0.0;

// This is the absolute linear position the code expects after the command
float targetLinearAbsoluteMM = 0.0;

// This is the positive travel distance used for stopping
float targetLinearMagnitudeMM = 0.0;

// Motor revolutions and pulses needed for the requested linear motion
float targetLinearRevolutions = 0.0;
long targetLinearPulses = 0;

// Direction sign for the requested linear movement
int linearMovementSign = +1;

// Runtime state for the linear axis
bool linearDone = true;
long linearPulsesSent = 0;
long signedLinearCount = 0;
float measuredLinearMotorDeg = 0.0;
float measuredLinearUreteroMM = 0.0;

///---------------------------------------------- Rotation Target State -------------------------------------------
// Rotation input is relative ureteroscope rotation in degrees
float targetUreteroscopeRotationDeg = 0.0;

// Required motor angle for the requested ureteroscope rotation
float targetRotationMotorDeg = 0.0;
float targetRotationMotorMagnitudeDeg = 0.0;

// Estimated motor pulses used for printing and backup stop
long targetRotationPulses = 0;

// Direction sign for the requested rotation movement
int rotationMovementSign = +1;

// Runtime state for the rotation axis
bool rotationDone = true;
long rotationPulsesSent = 0;
long signedRotationCount = 0;
float measuredRotationMotorDeg = 0.0;
float measuredUreteroRotationDeg = 0.0;

///---------------------------------------------- Flexion Target State --------------------------------------------

// Flexion input is the desired absolute tip flexion angle
float targetTipDeg = 0.0;

// These are selected for each command from the absolute target-angle range
float selectedFlexionTwistFactor = flexionTwistFactor0To90;
float selectedFlexionTipGain = flexionTwistFactor0To90 / flexionGearRatio;

// Required ST3020 motor angle for the requested tip angle
float targetFlexionMotorDeg = 0.0;

// Physical ST3020 angle after shifting -180 to +180 onto 0 to 360
float targetFlexionPhysicalDeg = 0.0;

// ST3020 target encoder step
int targetFlexionSteps = flexionNeutralStep;

// Speed selected from the absolute value of the requested tip angle
// A larger flexion target above 100 degrees produces a smaller and slower speed command
int selectedFlexionSpeed = servo_speed;

// Runtime state for the flexion axis
bool flexionDone = true;
int currentFlexionStep = -1;
int lastMovingFlexionStep = -1;
float measuredFlexionMotorDeg = 0.0;
float measuredTipDeg = 0.0;

///---------------------------------------------- Timing State -----------------------------------------------------

// These are reset at the beginning of every command
unsigned long lastPrintTime = 0;
unsigned long lastFlexionReadTime = 0;
unsigned long lastFlexionChangeTime = 0;

///--------------------------------------------- Function Prototypes ----------------------------------------------

// Setup Functions
void linearSetup();
void rotationSetup();
void flexionSetup();

// Startup and Prompt Functions
void diagnostics();
void linearDiagnostics();
void rotationDiagnostics();
void flexionDiagnostics();
void printFlexionTuningSummary();
void printLinearZeroReminder();
void printRotationNeutralReminder();
void printCommandPrompt();

// Serial Input Functions
bool parseMovementLine(const char inputLine[]);
void clearSerialInput();

// Target Calculation Functions
bool calculateAllTargets();
bool calculateLinearTarget();
bool calculateRotationTarget();
float selectFlexionTwistFactor(float tipDeg);
bool calculateFlexionTarget();
bool linearTargetIsInsideRange();
bool flexionTargetIsInsideRange();
int calculateFlexionSpeed();
void printFlexionOverstretchWarning();

// Movement Organization Functions
void moveAllAxesTogether();
void resetMovementMeasurements();
void printRequestedTargets();
void prepareMotorsForMovement();
void startFlexionMovement();
void runSimultaneousMovementLoop();
void pulseActiveSteppers();
void readLinearFeedback();
void readRotationFeedback();
void readFlexionFeedbackIfReady();
void printMovementStatusIfReady();
void updateAbsoluteLinearPosition();
void updateAbsoluteRotationPosition();
void printFinalSummary();

// Encoder Functions
void linearEncoderISR();
void rotationEncoderISR();
long getLinearEncoderCount();
long getRotationEncoderCount();
void resetLinearEncoder();
void resetRotationEncoder();

// General Function
void disableAllMotors();
bool inputLineEqualsWord(const char inputLine[], const char word[]);
void setHomeCommandTargets();
float normalizeRotationMapDeg(float angleDeg);

///-------------------------------------------------- Linear Setup -------------------------------------------------

void linearSetup() {
  // Configure TB6600 movement pins as Teensy outputs
  pinMode(linear_stepPin, OUTPUT);
  pinMode(linear_dirPin, OUTPUT);
  pinMode(linear_enaPin, OUTPUT);

  // Begin with no STEP pulse and with the driver enabled
  digitalWrite(linear_stepPin, LOW);
  digitalWrite(linear_dirPin, linear_dirForward);
  digitalWrite(linear_enaPin, enaPin_Enable);

  // Enable Teensy internal pull-up resistors on both encoder channels
  pinMode(linear_encA, INPUT_PULLUP);
  pinMode(linear_encB, INPUT_PULLUP);

  // Run linearEncoderISR whenever encoder channel A changes from LOW to HIGH
  attachInterrupt(digitalPinToInterrupt(linear_encA), linearEncoderISR, RISING);

  // Start each command from an encoder count of 0
  resetLinearEncoder();
}

///------------------------------------------------- Rotation Setup ------------------------------------------------

void rotationSetup() {
  // Configure TB6600 movement pins as Teensy outputs
  pinMode(rotation_stepPin, OUTPUT);
  pinMode(rotation_dirPin, OUTPUT);
  pinMode(rotation_enaPin, OUTPUT);

  // Begin with no STEP pulse and with the driver enabled
  digitalWrite(rotation_stepPin, LOW);
  digitalWrite(rotation_dirPin, rotation_dirClockwise);
  digitalWrite(rotation_enaPin, enaPin_Enable);

  // Enable Teensy internal pull-up resistors on both encoder channels
  pinMode(rotation_encA, INPUT_PULLUP);
  pinMode(rotation_encB, INPUT_PULLUP);

  // Run rotationEncoderISR whenever encoder channel A changes from LOW to HIGH
  attachInterrupt(digitalPinToInterrupt(rotation_encA), rotationEncoderISR, RISING);

  // Start each command from an encoder count of 0
  resetRotationEncoder();
}

///-------------------------------------------------- Flexion Setup ------------------------------------------------

void flexionSetup() {
  // Start Serial1 at the ST3020 factory-default communication speed
  // Teensy pin 0 is RX1 and Teensy pin 1 is TX1
  Serial1.begin(servo_baud);

  // Tell the SCServo library to communicate through Serial1
  servo.pSerial = &Serial1;

  // Ask the servo to move to neutral during startup
  servo.WritePosEx(servo_ID, flexionNeutralStep, servo_speed, servo_acceleration);
}

///------------------------------------------------ Diagnostics ---------------------------------------------------

void diagnostics() {
  Serial.println("\n-------------------- DIAGNOSTICS --------------------");
  linearDiagnostics();
  rotationDiagnostics();
  flexionDiagnostics();
  Serial.println("-----------------------------------------------------");
}

void linearDiagnostics() {
  Serial.println("\nLinear Axis Diagnostics");

  // Reading an output pin reports the logic level commanded by the Teensy
  // It does not prove that the motor driver received the signal
  Serial.print("ENA Pin (expected 0): ");
  Serial.println(digitalRead(linear_enaPin));
  Serial.print("DIR Pin: ");
  Serial.println(digitalRead(linear_dirPin));
  Serial.print("STEP Pin: ");
  Serial.println(digitalRead(linear_stepPin));
  Serial.print("Pulses per Motor Revolution: ");
  Serial.println(linearPulsesPerRev, 0);

  // Clear the encoder count before printing the diagnostic count
  resetLinearEncoder();

  Serial.print("Encoder Count: ");
  Serial.println(getLinearEncoderCount());

  Serial.print("Tracked Absolute Linear Position: ");
  Serial.print(currentLinearPositionMM, 3);
  Serial.println(" mm");
}

void rotationDiagnostics() {
  Serial.println("\nRotation Axis Diagnostics");

  // Reading an output pin reports the logic level commanded by the Teensy
  // It does not prove that the motor driver received the signal
  Serial.print("ENA Pin (expected 0): ");
  Serial.println(digitalRead(rotation_enaPin));
  Serial.print("DIR Pin: ");
  Serial.println(digitalRead(rotation_dirPin));
  Serial.print("STEP Pin: ");
  Serial.println(digitalRead(rotation_stepPin));
  Serial.print("Pulses per Motor Revolution: ");
  Serial.println(rotationPulsesPerRev, 0);

  // Clear the encoder count before printing the diagnostic count
  resetRotationEncoder();

  Serial.print("Encoder Count: ");
  Serial.println(getRotationEncoderCount());
}

void flexionDiagnostics() {
  Serial.println("\nFlexion Axis Diagnostics");

  // Ping returns the detected servo ID or -1 when no reply is received
  int detectedID = servo.Ping(servo_ID);

  if (detectedID == -1) {
    servoConnected = false;
    Serial.println("Servo Communication Failed");
    return;
  }

  servoConnected = true;
  Serial.print("Servo Connected with ID: ");
  Serial.println(detectedID);

  // Enable Servo Torque so the ST3020 can hold position and move
  int torqueAcknowledged = servo.EnableTorque(servo_ID, 1);
  Serial.print("Torque Enable Acknowledged: ");
  Serial.println(torqueAcknowledged == 1 ? "YES" : "NO");

  // Read servo supply voltage in tenths of a volt
  int rawVoltage = servo.ReadVoltage(servo_ID);
  Serial.print("Servo Supply Voltage: ");

  if (rawVoltage == -1) {
    Serial.println("READ FAILED");
  } else {
    Serial.print(rawVoltage / 10.0, 1);
    Serial.println(" V");
  }

  // Read servo internal temperature in degrees Celsius
  int temperatureC = servo.ReadTemper(servo_ID);
  Serial.print("Servo Temperature: ");

  if (temperatureC == -1) {
    Serial.println("READ FAILED");
  } else {
    Serial.print(temperatureC);
    Serial.println(" C");
  }
}

void printFlexionTuningSummary() {
  Serial.println("\n---------------- FLEXION CALIBRATION ----------------");
  Serial.print("Twist factor for 0 to 90 deg: ");
  Serial.println(flexionTwistFactor0To90, 4);
  Serial.print("Twist factor for over 90 to 180 deg: ");
  Serial.println(flexionTwistFactor90To180, 4);
  Serial.print("Twist factor for over 180 to 270 deg: ");
  Serial.println(flexionTwistFactor180To270, 4);
  Serial.print("Flexion gear ratio: ");
  Serial.println(flexionGearRatio, 4);
  Serial.print("Allowed absolute tip range: ");
  Serial.print(flexionMinTipDeg, 2);
  Serial.print(" deg to ");
  Serial.print(flexionMaxTipDeg, 2);
  Serial.println(" deg");
  Serial.print("Representable ST3020 motor range: ");
  Serial.print(flexionMinMotorDeg, 2);
  Serial.print(" deg to ");
  Serial.print(flexionMaxMotorDeg, 2);
  Serial.println(" deg");
  Serial.print("Speed reduction per tip degree beyond +/-100 deg: ");
  Serial.println(flexionSpeedReductionPerTipDeg, 1);
  Serial.println("Edit the three factors in the FLEXION CALIBRATION block near the top of this file.");
  Serial.println("-----------------------------------------------------");
}

///------------------------------------------------------ Setup ---------------------------------------------------

void motionSetup() {
  // Open USB communication with the Computer Serial Monitor
  Serial.begin(115200);

  // Limit how long readBytesUntil waits for the rest of the input line
  Serial.setTimeout(500);

  // Setup all three motor axes
  linearSetup();
  rotationSetup();
  flexionSetup();

  // The code assumes the TR8x4 axis starts at the physical 0 mm position
  currentLinearPositionMM = linearMinPositionMM;

  // The code assumes the ureteroscope starts physically flat at the rotation neutral position
  currentRotationMapDeg = 0.0;

  // Give the drivers adapter and servo time to start
  delay(1000);

  // Run startup diagnostics
  diagnostics();
  printFlexionTuningSummary();

  // Print the important absolute-position reminder after diagnostics
  printLinearZeroReminder();
  printRotationNeutralReminder();

  Serial.println("\nMotor Setup Complete");
  Serial.println("Enter one command with three numbers separated by spaces");
  Serial.println("Linear is RELATIVE, Rotation is RELATIVE, Flexion is ABSOLUTE");
  Serial.println("Example: 4 90 20");
  Serial.println("Type home or h to return to the home state");
}

void printLinearZeroReminder() {
  Serial.println("\n---------------- LINEAR ZERO REMINDER ----------------");
  Serial.println("Before sending movement commands, make sure the TR8x4 lead screw begins at 0 mm");
  Serial.println("This code will treat the startup position as absolute 0 mm");
  Serial.print("Allowed absolute linear range: ");
  Serial.print(linearMinPositionMM, 1);
  Serial.print(" mm to ");
  Serial.print(linearMaxPositionMM, 1);
  Serial.println(" mm");
  Serial.println("------------------------------------------------------");
}

void printRotationNeutralReminder() {
  Serial.println("\n-------------- ROTATION NEUTRAL REMINDER ------------");
  Serial.println("Before sending movement commands, make sure the ureteroscope is flat at rotation neutral");
  Serial.println("This code does not enforce rotation min/max range");
  Serial.println("This startup flat position becomes 0 degrees on the rotation map");
  Serial.println("Rotation commands are relative, but the code tracks mapped absolute rotation");
  Serial.println("A full revolution back to 0 in either direction resets the map to 0 degrees");
  Serial.println("------------------------------------------------------");
}

///------------------------------------------------------- Loop ----------------------------------------------------



void printCommandPrompt() {
  // Terse mode keeps only the line the host driver synchronises on.
  if (terseOutput) {
    Serial.println("\nPOSITIONING: Linear = RELATIVE | Rotation = RELATIVE | Flexion = ABSOLUTE");
    return;
  }
  // The first number is RELATIVE linear movement from the current tracked position
  // The second number is RELATIVE rotation in ureteroscope degrees
  // The third number is an ABSOLUTE tip-flexion target in degrees
  // Type home or h to return all three axes to the software home state
  Serial.println("\nPOSITIONING: Linear = RELATIVE | Rotation = RELATIVE | Flexion = ABSOLUTE");
  Serial.println("Enter Linear Additional(mm) Rotation Additional(deg) Flexion Target(deg):");

  Serial.print("Current absolute linear position: ");
  Serial.print(currentLinearPositionMM, 3);
  Serial.println(" mm");

  Serial.print("Current mapped rotation position: ");
  Serial.print(currentRotationMapDeg, 2);
  Serial.println(" deg");

  Serial.print("Linear range allowed: ");
  Serial.print(linearMinPositionMM, 1);
  Serial.print(" mm to ");
  Serial.print(linearMaxPositionMM, 1);
  Serial.println(" mm");

  Serial.println("Return to home state with: home OR h");
}

///------------------------------------------------ Serial Input --------------------------------------------------

bool parseMovementLine(const char inputLine[]) {
  // The dispatcher has already read the line and decided it is not a
  // laser command, so this only has to parse.
  homeCommandRequested = false;

  // The word home returns all three axes to the software home state
  // This check ignores capitalization, so home, Home, and HOME all work
  // The single letter h also works as a shortcut
  if (inputLineEqualsWord(inputLine, "home") || inputLineEqualsWord(inputLine, "h")) {
    setHomeCommandTargets();
    return true;
  }

  // A fourth value or any extra text makes the command invalid
  // sscanf tries to read Linear, Rotation, Flexion, and then one extra character
  // A correct command reads only the first three numbers
  char extraCharacter;
  int valuesRead = sscanf(inputLine, " %f %f %f %c", &requestedLinearMM, &requestedRotationDeg, &requestedFlexionDeg, &extraCharacter);

  if (valuesRead != 3) {
    // Wrong number of values, text, commas, or extra values will arrive here
    return false;
  }

  if (!isfinite(requestedLinearMM) || !isfinite(requestedRotationDeg) || !isfinite(requestedFlexionDeg)) {
    // Reject unusual values such as NaN (Not a Number) or infinity
    return false;
  }

  return true;
}

void clearSerialInput() {
  // Remove carriage return newline and extra characters after the command
  while (Serial.available() > 0) {
    Serial.read();
  }
}

bool inputLineEqualsWord(const char inputLine[], const char word[]) {
  // Compare a Serial Monitor line with a single word while ignoring capitalization
  // Leading and trailing spaces are ignored

  // Skips Leading Whitespace
  // Start at the very beginning index (0) of the input line
  int inputStart = 0;
  
  // Move the starting index forward as long as the character is a space, tab, or carriage return
  while (inputLine[inputStart] == ' ' || inputLine[inputStart] == '\t' || inputLine[inputStart] == '\r') {
    inputStart++; // Move to the next character
  }

  // Find the End of the String
  // Start looking for the end of the text, beginning from where the actual text starts
  int inputEnd = inputStart;
  
  // Loop until we find the null terminator ('\0'), which marks the absolute end of a C-string
  while (inputLine[inputEnd] != '\0') {
    inputEnd++; // Move forward until we find the end marker
  }

  // Trim Trailing Whitespace
  // Work backward from the end of the string to look for spaces, tabs, or returns
  // Make sure we don't accidentally back up past our starting point (inputEnd > inputStart)
  while (inputEnd > inputStart &&
         (inputLine[inputEnd - 1] == ' ' ||
          inputLine[inputEnd - 1] == '\t' ||
          inputLine[inputEnd - 1] == '\r')) {
    inputEnd--; // Pull the end boundary back by one character
  }

  // Measure the Target Word
  int wordLength = 0;
  // Count the characters in the target word until we hit its null terminator
  while (word[wordLength] != '\0') {
    wordLength++;
  }

  // Quick Length Check
  // (inputEnd - inputStart) calculates the exact length of the cleaned-up input line
  // If the lengths don't match, they can't possibly be the same word
  if (inputEnd - inputStart != wordLength) {
    return false; // Exit early because the lengths are different
  }

  // Character-by-Character Comparison
  // Loop through each character of both strings based on the target word's length
  for (int i = 0; i < wordLength; i++) {
    // Grab the current character from the input line (offset by where the real text started)
    char inputChar = inputLine[inputStart + i];
    // Grab the current character from the target word
    char wordChar = word[i];

    // Convert inputChar to lowercase if it is an uppercase letter ('A' through 'Z')
    // Adding 32 shifts the ASCII value from uppercase to lowercase
    if (inputChar >= 'A' && inputChar <= 'Z') {
      inputChar = inputChar + 32;
    }

    // Convert wordChar to lowercase if it is an uppercase letter
    if (wordChar >= 'A' && wordChar <= 'Z') {
      wordChar = wordChar + 32;
    }

    // Now that both are lowercase, compare them 
    // If they don't match, the words are not the same
    if (inputChar != wordChar) {
      return false; // Mis-match found, exit and return false
    }
  }

  // If the code successfully makes it through the entire loop without returning false,
  // it means the cleaned-up input perfectly matches the target word
  return true;
}

void setHomeCommandTargets() {
  // The home state is linear 0 mm, rotation map 0 degrees, and flexion tip 0 degrees
  // Linear and rotation are controlled by relative moves, so the code calculates the needed relative command
  // Flexion is already an absolute tip target, so its home command is simply 0 degrees

  homeCommandRequested = true;

  requestedLinearMM = linearMinPositionMM - currentLinearPositionMM;
  requestedRotationDeg = -currentRotationMapDeg;
  requestedFlexionDeg = 0.0;

  Serial.println("\nHome command received");
  Serial.println("Target home state: Linear 0 mm, Rotation 0 deg, Flexion 0 deg");
}

///-------------------------------------------- Target Calculations -----------------------------------------------

bool calculateAllTargets() {
  // All targets are calculated before motion begins
  // This lets the code reject the full command before any motor starts moving

  if (!calculateLinearTarget()) {
    return false;
  }

  if (!calculateRotationTarget()) {
    return false;
  }

  if (!calculateFlexionTarget()) {
    return false;
  }

  return true;
}

bool calculateLinearTarget() {
  // Linear input is additional movement relative to the current tracked absolute position
  targetLinearRelativeMM = requestedLinearMM;

  // This is the absolute position the linear axis would reach if the command is allowed
  targetLinearAbsoluteMM = currentLinearPositionMM + targetLinearRelativeMM;

  // Reject the entire 3-DOF command if linear motion would go outside 0 mm to 177 mm
  if (!linearTargetIsInsideRange()) {
    return false;
  }

  // Positive input moves forward and negative input moves backward
  linearMovementSign = (targetLinearRelativeMM > 0.0 ? +1 : -1);

  // Use absolute value because stopping only cares about travel distance
  targetLinearMagnitudeMM = fabsf(targetLinearRelativeMM);

  // Convert requested millimeters into motor revolutions
  targetLinearRevolutions = targetLinearMagnitudeMM / linearMMPerRev;

  // Convert motor revolutions into STEP pulses for the TB6600
  targetLinearPulses = lroundf(targetLinearRevolutions * linearPulsesPerRev);

  // If targetLinearPulses is 0, there is no linear movement to execute
  linearDone = (targetLinearPulses == 0);

  return true;
}

bool linearTargetIsInsideRange() {
  // Tiny tolerance prevents floating-point roundoff from rejecting values at exactly 0 or 177
  bool belowMinimum = targetLinearAbsoluteMM < linearMinPositionMM - linearRangeToleranceMM;
  bool aboveMaximum = targetLinearAbsoluteMM > linearMaxPositionMM + linearRangeToleranceMM;

  if (belowMinimum || aboveMaximum) {
    Serial.println("\nLinear Range Error");
    Serial.println("No motors will move because the linear command would leave the allowed range");

    Serial.print("Current absolute linear position: ");
    Serial.print(currentLinearPositionMM, 3);
    Serial.println(" mm");

    Serial.print("Requested additional linear movement: ");
    Serial.print(targetLinearRelativeMM, 3);
    Serial.println(" mm");

    Serial.print("Requested absolute linear position: ");
    Serial.print(targetLinearAbsoluteMM, 3);
    Serial.println(" mm");

    Serial.print("Allowed absolute linear range: ");
    Serial.print(linearMinPositionMM, 1);
    Serial.print(" mm to ");
    Serial.print(linearMaxPositionMM, 1);
    Serial.println(" mm");

    return false;
  }

  // If the target is almost exactly the minimum, clean it to exactly 0
  if (targetLinearAbsoluteMM < linearMinPositionMM) {
    targetLinearAbsoluteMM = linearMinPositionMM;
  }

  // If the target is almost exactly the maximum, clean it to exactly 177
  if (targetLinearAbsoluteMM > linearMaxPositionMM) {
    targetLinearAbsoluteMM = linearMaxPositionMM;
  }

  return true;
}

bool calculateRotationTarget() {
  // Rotation input is relative ureteroscope rotation in degrees
  targetUreteroscopeRotationDeg = requestedRotationDeg;

  // Positive rotation input and negative rotation input use opposite directions
  rotationMovementSign = (targetUreteroscopeRotationDeg > 0.0 ? +1 : -1);

  // Convert ureteroscope rotation into required motor rotation
  targetRotationMotorDeg = rotationGearRatio * targetUreteroscopeRotationDeg;

  // Use absolute value because stopping only cares about angle traveled
  targetRotationMotorMagnitudeDeg = fabsf(targetRotationMotorDeg);

  // Estimate STEP pulses from motor degrees
  // Encoder feedback is still the main stopping method
  targetRotationPulses = lroundf((targetRotationMotorMagnitudeDeg / degreesPerRevolution) * rotationPulsesPerRev);

  // If targetRotationPulses is 0, there is no rotation movement to execute
  rotationDone = (targetRotationPulses == 0);

  return true;
}

float selectFlexionTwistFactor(float tipDeg) {
  // Use absolute angle so the same calibration ranges apply in both directions
  float absoluteTipDeg = fabsf(tipDeg);

  if (absoluteTipDeg <= 90.0) {
    return flexionTwistFactor0To90;
  }

  if (absoluteTipDeg <= 180.0) {
    return flexionTwistFactor90To180;
  }

  return flexionTwistFactor180To270;
}

bool calculateFlexionTarget() {
  // Flexion input is the desired absolute tip flexion angle
  targetTipDeg = requestedFlexionDeg;

  // Select one twist factor from the absolute target-angle range
  selectedFlexionTwistFactor = selectFlexionTwistFactor(targetTipDeg);
  selectedFlexionTipGain = selectedFlexionTwistFactor / flexionGearRatio;

  // Convert desired tip angle into required ST3020 motor angle
  targetFlexionMotorDeg = targetTipDeg / selectedFlexionTipGain;

  // Reject the entire 3-DOF command if the requested flexion is outside the servo range
  if (!flexionTargetIsInsideRange()) {
    return false;
  }

  // Shift motor angle from -180 to +180 into the servo's 0 to 360 scale
  targetFlexionPhysicalDeg = targetFlexionMotorDeg + halfRevolutionDegrees;

  // Convert physical motor angle into ST3020 encoder steps
  targetFlexionSteps = lroundf((targetFlexionPhysicalDeg * servoMaximumStep) / degreesPerRevolution);

  // Select a slower speed when the requested absolute tip angle is above 100 degrees
  selectedFlexionSpeed = calculateFlexionSpeed();

  // Print one warning that matches the largest warning level reached by this target
  printFlexionOverstretchWarning();

  // If the servo is not connected, do not wait for flexion feedback
  // Nothing to wait for if the servo is absent, or if this command asks
  // for the flexion angle the servo was already sent to.
  flexionDone = !servoConnected || (targetFlexionSteps == lastCommandedFlexionSteps);

  return true;
}

int calculateFlexionSpeed() {
  // Use absolute value so +150 degrees and -150 degrees receive the same speed
  float absoluteTargetTipDeg = fabsf(targetTipDeg);

  // Targets through 100 degrees use the normal slow steady speed
  if (absoluteTargetTipDeg <= flexionSlowdownStartTipDeg) {
    return servo_speed;
  }

  // Find how many tip degrees the target is beyond the 100 degree slowdown point
  float degreesBeyondSlowdown = absoluteTargetTipDeg - flexionSlowdownStartTipDeg;

  // Reduce the speed by 2.5 speed units for each additional tip degree
  int speedReduction = lroundf(degreesBeyondSlowdown * flexionSpeedReductionPerTipDeg);
  int calculatedSpeed = servo_speed - speedReduction;

  // Keep the command from becoming slower than the backup minimum speed
  if (calculatedSpeed < flexionMinimumSpeed) {
    calculatedSpeed = flexionMinimumSpeed;
  }

  return calculatedSpeed;
}

void printFlexionOverstretchWarning() {
  // Warning thresholds are based on absolute tip angle so they apply in both directions
  float absoluteTargetTipDeg = fabsf(targetTipDeg);

  // Print only the highest warning level reached to keep the Serial Monitor clear
  // A target within one encoder count of the allowed maximum receives the maximum warning
  if (absoluteTargetTipDeg >= flexionMaxTipDeg - flexionRangeToleranceTipDeg) {
    Serial.println("WARNING: Reaching maximum allowed flexion");
  } else if (absoluteTargetTipDeg >= flexionMajorWarningTipDeg) {
    Serial.println("MAJOR PRECAUTION: Flexion target is near the maximum and may overstretch the ureteroscope");
  } else if (absoluteTargetTipDeg >= flexionModerateWarningTipDeg) {
    Serial.println("WARNING: High flexion target may overstretch the ureteroscope");
  } else if (absoluteTargetTipDeg >= flexionSmallWarningTipDeg) {
    Serial.println("CAUTION: Flexion target is entering the overstretch precaution range");
  }
}

bool flexionTargetIsInsideRange() {
  // Reject commands outside the exact -270 to +270 degree tip range or the
  // ST3020's representable -180 to +180 degree motor range
  bool belowTipMinimum = targetTipDeg < flexionMinTipDeg;
  bool aboveTipMaximum = targetTipDeg > flexionMaxTipDeg;
  bool belowMotorMinimum = targetFlexionMotorDeg < flexionMinMotorDeg;
  bool aboveMotorMaximum = targetFlexionMotorDeg > flexionMaxMotorDeg;

  if (belowTipMinimum || aboveTipMaximum || belowMotorMinimum || aboveMotorMaximum) {
    Serial.println("\nFlexion Range Error");
    Serial.println("No motors will move because the requested flexion is outside the allowed range");

    Serial.print("Requested tip flexion: ");
    Serial.print(targetTipDeg, 2);
    Serial.println(" deg");

    Serial.print("Required ST3020 motor angle: ");
    Serial.print(targetFlexionMotorDeg, 2);
    Serial.println(" deg");

    Serial.print("Selected flexionTwistFactor: ");
    Serial.println(selectedFlexionTwistFactor, 4);

    Serial.print("Selected flexionTipGain: ");
    Serial.println(selectedFlexionTipGain, 4);

    Serial.print("Representable ST3020 motor range: ");
    Serial.print(flexionMinMotorDeg, 1);
    Serial.print(" deg to ");
    Serial.print(flexionMaxMotorDeg, 1);
    Serial.println(" deg");

    Serial.print("Allowed requested tip range: ");
    Serial.print(flexionMinTipDeg, 1);
    Serial.print(" deg to ");
    Serial.print(flexionMaxTipDeg, 1);
    Serial.println(" deg");

    return false;
  }

  return true;
}

///----------------------------------------------- Encoder Interrupts --------------------------------------------

void linearEncoderISR() {
  // Read channel B every time channel A rises to determine encoder direction
  // 1x decoding means only one edge of channel A is counted
  if (digitalRead(linear_encB) == HIGH) {
    linearEncoderCount++;
  } else {
    linearEncoderCount--;
  }
}

void rotationEncoderISR() {
  // Read channel B every time channel A rises to determine encoder direction
  // 1x decoding means only one edge of channel A is counted
  if (digitalRead(rotation_encB) == HIGH) {
    rotationEncoderCount++;
  } else {
    rotationEncoderCount--;
  }
}

long getLinearEncoderCount() {
  // Pause interrupts so the encoder count cannot change halfway through reading it
  noInterrupts();
  long count = linearEncoderCount;
  interrupts();
  return count;
}

long getRotationEncoderCount() {
  // Pause interrupts so the encoder count cannot change halfway through reading it
  noInterrupts();
  long count = rotationEncoderCount;
  interrupts();
  return count;
}

void resetLinearEncoder() {
  // Clear the linear encoder count as one uninterrupted operation
  noInterrupts();
  linearEncoderCount = 0;
  interrupts();
}

void resetRotationEncoder() {
  // Clear the rotation encoder count as one uninterrupted operation
  noInterrupts();
  rotationEncoderCount = 0;
  interrupts();
}

///--------------------------------------------- Simultaneous Movement --------------------------------------------

void moveAllAxesTogether() {
  // This function is intentionally a short organizer
  // Each major part of the movement has its own smaller function below
  if (!terseOutput) {
    Serial.println("\nStarting 3-DOF Movement");
  }

  resetMovementMeasurements();
  printRequestedTargets();
  prepareMotorsForMovement();
  runSimultaneousMovementLoop();
  updateAbsoluteLinearPosition();
  updateAbsoluteRotationPosition();
  printFinalSummary();
}

void resetMovementMeasurements() {
  // Runtime counters and measured values are cleared at the start of each command
  linearPulsesSent = 0;
  rotationPulsesSent = 0;

  signedLinearCount = 0;
  signedRotationCount = 0;

  measuredLinearMotorDeg = 0.0;
  measuredLinearUreteroMM = 0.0;
  measuredRotationMotorDeg = 0.0;
  measuredUreteroRotationDeg = 0.0;

  currentFlexionStep = -1;
  lastMovingFlexionStep = -1;
  measuredFlexionMotorDeg = 0.0;
  measuredTipDeg = 0.0;

  lastPrintTime = 0;
  lastFlexionReadTime = 0;
  lastFlexionChangeTime = millis();
}

void printRequestedTargets() {
  // ~500 bytes of pre-move report. The host already knows what it asked for.
  if (terseOutput) {
    return;
  }
  // Print everything the code calculated before motion begins
  // This helps check whether the math matches the intended movement

  Serial.print("Linear current absolute position: ");
  Serial.print(currentLinearPositionMM, 3);
  Serial.println(" mm");

  Serial.print("Linear requested additional movement: ");
  Serial.print(targetLinearRelativeMM, 3);
  Serial.println(" mm");

  Serial.print("Linear target absolute position: ");
  Serial.print(targetLinearAbsoluteMM, 3);
  Serial.println(" mm");

  Serial.print("Linear Motor Revolutions: ");
  Serial.println(targetLinearRevolutions, 3);

  Serial.print("Linear Estimated STEP Pulses: ");
  Serial.println(targetLinearPulses);

  Serial.print("Rotation Target: ");
  Serial.print(targetUreteroscopeRotationDeg, 2);
  Serial.println(" deg ureteroscope");

  Serial.print("Rotation Map Target: ");
  Serial.print(normalizeRotationMapDeg(currentRotationMapDeg + targetUreteroscopeRotationDeg), 2);
  Serial.println(" deg");

  Serial.print("Rotation Required Motor Angle: ");
  Serial.print(targetRotationMotorDeg, 2);
  Serial.println(" deg motor");

  Serial.print("Rotation Estimated STEP Pulses: ");
  Serial.println(targetRotationPulses);

  Serial.print("Flexion Target: ");
  Serial.print(targetTipDeg, 2);
  Serial.println(" deg tip");

  Serial.print("Flexion Selected Twist Factor: ");
  Serial.println(selectedFlexionTwistFactor, 4);

  Serial.print("Flexion Selected Tip Gain: ");
  Serial.println(selectedFlexionTipGain, 4);

  Serial.print("Flexion Required Motor Angle: ");
  Serial.print(targetFlexionMotorDeg, 2);
  Serial.println(" deg motor");

  Serial.print("Flexion ST3020 Target Step: ");
  Serial.println(targetFlexionSteps);

  Serial.print("Flexion Selected Speed: ");
  Serial.println(selectedFlexionSpeed);
}

void prepareMotorsForMovement() {
  // Set the linear direction only if linear movement is needed
  if (!linearDone) {
    digitalWrite(linear_dirPin, linearMovementSign > 0 ? linear_dirForward : linear_dirBackward);
  }

  // Set the rotation direction only if rotation movement is needed
  if (!rotationDone) {
    digitalWrite(rotation_dirPin, rotationMovementSign > 0 ? rotation_dirClockwise : rotation_dirCounter);
  }

  // Give direction pins a tiny moment to settle before the first pulse
  delayMicroseconds(directionSetup_us);

  // Reset encoders so each command is measured from 0
  resetLinearEncoder();
  resetRotationEncoder();

  // Keep both TB6600 drivers enabled so they can move and hold position
  digitalWrite(linear_enaPin, enaPin_Enable);
  digitalWrite(rotation_enaPin, enaPin_Enable);

  // Start the ST3020 before the stepper pulse loop
  startFlexionMovement();
}

void startFlexionMovement() {
  // Already satisfied -- do not re-issue the same position command.
  if (flexionDone) {
    return;
  }
  // The ST3020 receives one command and then moves internally
  // This lets it move while the Teensy is pulsing the stepper drivers

  if (!servoConnected) {
    Serial.println("Flexion Skipped because ST3020 Communication is Unavailable");
    flexionDone = true;
    return;
  }

  int torqueAcknowledged = servo.EnableTorque(servo_ID, 1);

  if (torqueAcknowledged != 1) {
    Serial.println("ST3020 did not Acknowledge Torque Enable");
    flexionDone = true;
    return;
  }

  // Use the target-based speed calculated from the requested absolute tip angle
  // Larger absolute targets above 100 degrees use a smaller and slower speed value
  int commandAcknowledged = servo.WritePosEx(servo_ID, targetFlexionSteps, selectedFlexionSpeed, servo_acceleration);

  if (commandAcknowledged != 1) {
    Serial.println("ST3020 did not Acknowledge the Movement Command");
    flexionDone = true;
    return;
  }

  // Start the no-change timer after the command is accepted
  lastFlexionChangeTime = millis();
  lastCommandedFlexionSteps = targetFlexionSteps;

  // Host mode is fire-and-forget. Re-commanding an absolute target 20x a
  // second restarts the servo's acceleration ramp before it ever reaches
  // speed, which is what makes flexion feel like it is clicking rather
  // than moving. Issue the command and let the servo get on with it; the
  // host sends a fresh target on the next tick anyway.
  if (terseOutput) {
    flexionDone = true;
  }
}

void runSimultaneousMovementLoop() {
  // Backup pulse limits stop the code from pulsing forever if encoder feedback fails
  // Encoder feedback is still the normal stopping method
  // Allow up to 300 extra pulses before assuming encoder feedback did not reach the target
  // For linear, 300 pulses is about 0.75 mm because 300 * 4 / 1600 = 0.75
  // For rotation, 300 pulses is about 67.5 motor degrees or 27 ureteroscope degrees
  long linearBackupPulseLimit = targetLinearPulses + 8;   // was 300 = 0.75 mm of overshoot per command
  long rotationBackupPulseLimit = targetRotationPulses + 8;   // was 300

  // Continue until every axis has finished or has been skipped
  while (!linearDone || !rotationDone || !flexionDone) {
    pulseActiveSteppers();

    readLinearFeedback();
    readRotationFeedback();
    readFlexionFeedbackIfReady();

    // Check backup pulse limits inside the loop after feedback has had a chance to update
    if (!linearDone && linearPulsesSent >= linearBackupPulseLimit) {
      Serial.println("Linear stopped because encoder target was not reached");
      linearDone = true;
    }

    if (!rotationDone && rotationPulsesSent >= rotationBackupPulseLimit) {
      Serial.println("Rotation stopped because encoder target was not reached");
      rotationDone = true;
    }

    printMovementStatusIfReady();

    // If only the servo is still moving, pause briefly so the loop does not spin too fast
    if (linearDone && rotationDone && !flexionDone) {
      delay(5);
    }
  }
}

void pulseActiveSteppers() {
  // A stepper is pulsed only if that axis still needs to move
  bool pulseLinear = !linearDone;
  bool pulseRotation = !rotationDone;

  // Set active STEP pins HIGH at the same time
  // This is what makes the two stepper axes move together
  if (pulseLinear) {
    digitalWrite(linear_stepPin, HIGH);
  }

  if (pulseRotation) {
    digitalWrite(rotation_stepPin, HIGH);
  }

  // Hold STEP HIGH long enough for the TB6600 to detect the pulse
  if (pulseLinear || pulseRotation) {
    delayMicroseconds(stepDelay_us);
  }

  // Set active STEP pins LOW at the same time
  if (pulseLinear) {
    digitalWrite(linear_stepPin, LOW);
    linearPulsesSent++;
  }

  if (pulseRotation) {
    digitalWrite(rotation_stepPin, LOW);
    rotationPulsesSent++;
  }

  // Hold STEP LOW before the next pulse
  if (pulseLinear || pulseRotation) {
    delayMicroseconds(stepDelay_us);
  }
}

void readLinearFeedback() {
  // Do not read or update a completed linear axis
  if (linearDone) {
    return;
  }

  // Read raw encoder count from the interrupt-updated variable
  long rawLinearCount = getLinearEncoderCount();

  // Apply sign correction so positive command can print as positive motion
  signedLinearCount = linearEncoderSign * rawLinearCount;

  // Convert encoder counts into measured motor angle
  measuredLinearMotorDeg = (signedLinearCount * degreesPerRevolution) / linearEncoderCPR;

  // Convert encoder counts into measured ureteroscope linear motion
  measuredLinearUreteroMM = (signedLinearCount * linearMMPerRev) / linearEncoderCPR;

  // Stop linear axis when measured travel reaches requested travel
  if (fabsf(measuredLinearUreteroMM) >= targetLinearMagnitudeMM - linearStopMarginMM) {
    linearDone = true;
  }
}

void readRotationFeedback() {
  // Do not read or update a completed rotation axis
  if (rotationDone) {
    return;
  }

  // Read raw encoder count from the interrupt-updated variable
  long rawRotationCount = getRotationEncoderCount();

  // Apply sign correction so positive command can print as positive motion
  signedRotationCount = rotationEncoderSign * rawRotationCount;

  // Convert encoder counts into measured motor angle
  measuredRotationMotorDeg = (signedRotationCount * degreesPerRevolution) / rotationEncoderCPR;

  // Convert measured motor angle into measured ureteroscope rotation
  measuredUreteroRotationDeg = measuredRotationMotorDeg / rotationGearRatio;

  // Stop rotation axis when measured motor angle reaches required motor angle
  if (fabsf(measuredRotationMotorDeg) >= targetRotationMotorMagnitudeDeg - rotationStopMarginMotorDeg) {
    rotationDone = true;
  }
}

void readFlexionFeedbackIfReady() {
  // Do not read or update a completed flexion axis
  if (flexionDone) {
    return;
  }

  // Read the ST3020 only at the print interval so the serial bus is not flooded
  if (millis() - lastFlexionReadTime < printInterval_ms) {
    return;
  }

  // Read the current ST3020 encoder position
  currentFlexionStep = servo.ReadPos(servo_ID);

  if (currentFlexionStep == -1) {
    Serial.println("ST3020 Position Read Failed");
    flexionDone = true;
    return;
  }

  // Track the last time the flexion encoder actually changed
  if (lastMovingFlexionStep == -1 || currentFlexionStep != lastMovingFlexionStep) {
    lastMovingFlexionStep = currentFlexionStep;
    lastFlexionChangeTime = millis();
  }

  // Convert current encoder position into signed motor angle
  measuredFlexionMotorDeg =
    (currentFlexionStep * degreesPerRevolution / (float)servoMaximumStep) - halfRevolutionDegrees;

  // Convert motor angle using the gain selected for this command's target range
  measuredTipDeg = measuredFlexionMotorDeg * selectedFlexionTipGain;

  // Stop flexion axis when servo reaches target step within the margin
  if (abs(currentFlexionStep - targetFlexionSteps) <= flexionStopMarginSteps) {
    flexionDone = true;
  }

  // If the servo has stopped changing position, assume it cannot reach the exact target
  // This is usually caused by a mechanical limit, load, or a target that is too close to the physical end range
  if (!flexionDone && millis() - lastFlexionChangeTime > flexionNoChangeTimeout_ms) {
    Serial.println("Flexion stopped moving before reaching the exact target");
    Serial.println("Ending movement so the Serial Monitor does not print forever");
    flexionDone = true;
  }

  lastFlexionReadTime = millis();
}

void printMovementStatusIfReady() {
  if (terseOutput) {
    return;
  }
  // Printing one combined line keeps the Serial Monitor readable during simultaneous motion
  // Printing takes time, so very frequent printing can slow stepper pulse timing
  if (millis() - lastPrintTime < printInterval_ms) {
    return;
  }

  Serial.print("Linear Abs mm, Rel mm, Count: ");
  Serial.print(currentLinearPositionMM + measuredLinearUreteroMM, 3);
  Serial.print(", ");
  Serial.print(measuredLinearUreteroMM, 3);
  Serial.print(", ");
  Serial.print(signedLinearCount);

  Serial.print(" | Rotation Motor Deg, Ureteroscope Deg, Count: ");
  Serial.print(measuredRotationMotorDeg, 2);
  Serial.print(", ");
  Serial.print(measuredUreteroRotationDeg, 2);
  Serial.print(", ");
  Serial.print(signedRotationCount);

  Serial.print(" | Rotation Map Deg: ");
  Serial.print(normalizeRotationMapDeg(currentRotationMapDeg + measuredUreteroRotationDeg), 2);

  Serial.print(" | Flexion Step, Motor Deg, Tip Deg: ");
  Serial.print(currentFlexionStep);
  Serial.print(", ");
  Serial.print(measuredFlexionMotorDeg, 2);
  Serial.print(", ");
  Serial.println(measuredTipDeg, 2);

  lastPrintTime = millis();
}

void updateAbsoluteLinearPosition() {
  // Absolute position is updated after movement using the measured encoder-based linear travel
  // This means the tracker follows measured motion instead of assuming the motor completed perfectly

  float previousLinearPositionMM = currentLinearPositionMM;
  currentLinearPositionMM =
    currentLinearPositionMM + (linearMovementSign * fabsf(measuredLinearUreteroMM));

  // Clean up tiny roundoff near the lower limit
  if (currentLinearPositionMM < linearMinPositionMM && currentLinearPositionMM > linearMinPositionMM - linearRangeToleranceMM) {
    currentLinearPositionMM = linearMinPositionMM;
  }

  // Clean up tiny roundoff near the upper limit
  if (currentLinearPositionMM > linearMaxPositionMM && currentLinearPositionMM < linearMaxPositionMM + linearRangeToleranceMM) {
    currentLinearPositionMM = linearMaxPositionMM;
  }

  Serial.print("Linear absolute position updated from ");
  Serial.print(previousLinearPositionMM, 3);
  Serial.print(" mm to ");
  Serial.print(currentLinearPositionMM, 3);
  Serial.println(" mm");
}

void updateAbsoluteRotationPosition() {
  // Rotation map position is updated after movement using measured encoder-based ureteroscope rotation
  // Startup flat position is 0 degrees
  // Full revolutions wrap back to 0 degrees

  float previousRotationMapDeg = currentRotationMapDeg;
  currentRotationMapDeg = normalizeRotationMapDeg(
    currentRotationMapDeg + (rotationMovementSign * fabsf(measuredUreteroRotationDeg)));

  Serial.print("Rotation map updated from ");
  Serial.print(previousRotationMapDeg, 2);
  Serial.print(" deg to ");
  Serial.print(currentRotationMapDeg, 2);
  Serial.println(" deg");
}

void printFinalSummary() {
  // Terse: only the three lines the host parses position out of.
  if (terseOutput) {
    Serial.println("3-DOF Movement Complete");
    Serial.print("Final Linear Absolute Position: ");
    Serial.print(currentLinearPositionMM, 3);
    Serial.println(" mm");
    Serial.print("Final Rotation Map Position: ");
    Serial.print(currentRotationMapDeg, 2);
    Serial.println(" deg");
    Serial.print("Final Flexion Step, Motor Deg, Tip Deg: ");
    Serial.print(currentFlexionStep);
    Serial.print(", ");
    Serial.print(measuredFlexionMotorDeg, 2);
    Serial.print(", ");
    Serial.println(measuredTipDeg, 2);
    return;
  }
  Serial.println("\n3-DOF Movement Complete");

  Serial.print("Final Linear Absolute Position: ");
  Serial.print(currentLinearPositionMM, 3);
  Serial.println(" mm");

  Serial.print("Final Linear Relative Motion, Motor Deg, Count: ");
  Serial.print(measuredLinearUreteroMM, 3);
  Serial.print(", ");
  Serial.print(measuredLinearMotorDeg, 2);
  Serial.print(", ");
  Serial.println(signedLinearCount);

  Serial.print("Final Rotation Motor Deg, Ureteroscope Deg, Count: ");
  Serial.print(measuredRotationMotorDeg, 2);
  Serial.print(", ");
  Serial.print(measuredUreteroRotationDeg, 2);
  Serial.print(", ");
  Serial.println(signedRotationCount);

  Serial.print("Final Rotation Map Position: ");
  Serial.print(currentRotationMapDeg, 2);
  Serial.println(" deg");

  Serial.print("Final Flexion Step, Motor Deg, Tip Deg: ");
  Serial.print(currentFlexionStep);
  Serial.print(", ");
  Serial.print(measuredFlexionMotorDeg, 2);
  Serial.print(", ");
  Serial.println(measuredTipDeg, 2);
}

float normalizeRotationMapDeg(float angleDeg) {
  // Keep the rotation map inside one revolution in either direction
  // +360 degrees means the ureteroscope has returned to flat 0 from clockwise motion
  // -360 degrees means the ureteroscope has returned to flat 0 from counterclockwise motion

  while (angleDeg >= degreesPerRevolution) {
    angleDeg = angleDeg - degreesPerRevolution;
  }

  while (angleDeg <= -degreesPerRevolution) {
    angleDeg = angleDeg + degreesPerRevolution;
  }

  // Clean tiny encoder or floating-point error near 0
  if (fabsf(angleDeg) <= rotationMapZeroToleranceDeg) {
    angleDeg = 0.0;
  }

  return angleDeg;
}

///------------------------------------------------ Disable Motors ------------------------------------------------

void disableAllMotors() {
  // Disable both stepper drivers and force both STEP outputs LOW
  digitalWrite(linear_enaPin, enaPin_Disable);
  digitalWrite(rotation_enaPin, enaPin_Disable);
  digitalWrite(linear_stepPin, LOW);
  digitalWrite(rotation_stepPin, LOW);

  // Disable ST3020 torque if the servo was detected
  if (servoConnected) {
    servo.EnableTorque(servo_ID, 0);
  }
}

// =========================================================================
// Laser sketch, from shootingyesready_inoF-1.ino
// =========================================================================


// ---------------------------------------------------------------------------
// Build Identity
// ---------------------------------------------------------------------------

// Printed at boot and on [?]. If you reset the Teensy and do not see this
// banner, the board is running a DIFFERENT sketch and nothing in this file is
// in effect. Check the banner before trusting any test result.
const char* BUILD_NAME = "LASER-V5.2";
const char* BUILD_NOTE = "pin8 NO + edge-armed; fire confirmed working; [w] flips ready sense";

// ---------------------------------------------------------------------------
// Laser Pin Assignments
// ---------------------------------------------------------------------------

const int relay_laser = 8;
const int fire1_laser = 9;
const int fire2_laser = 10;

// ---------------------------------------------------------------------------
// Relay Board Electrical Facts
// ---------------------------------------------------------------------------

// All three boards are high-level-trigger type:
//   HIGH = coil energizes -> NO closes, NC opens
//   LOW  = coil releases  -> NO opens,  NC closes
const int COIL_ENERGIZED = HIGH;
const int COIL_RELEASED  = LOW;

// ---------------------------------------------------------------------------
// Ready Channel (pin 8)
// ---------------------------------------------------------------------------

// true  = pin 8 is on the NC terminal (contact closed when the coil releases)
// false = pin 8 is on the NO terminal (contact open when the coil releases)
//
// CHANGED TO false IN V5.2. Fire started working after an undocumented
// hardware change, and Ready stopped working in the same moment. Ready had
// been correct on NC, so whatever moved also flipped pin 8's sense - the
// wire is now behaving as NO. This is the matching software change.
//
// If Ready still does not arm, this assumption is wrong: send [w] to flip it
// back at runtime (no reflash) and tell me, because then the hardware change
// did something other than move pin 8.
// false as of 2026-09-03, decided on clean evidence rather than inference.
//
// Symptom: with fire working correctly, STANDBY and STOP both armed the machine
// while READY did not -- i.e. it armed on the edge our "open" produces. That is
// an inverted ready sense, and it is Bug 1's signature exactly.
//
// Earlier attempts to flip this were made while two host-side bugs were active
// (the motion driver was draining the laser's serial replies, and arm() was
// driving the fire relays), so every observation before those were fixed was
// unreliable. This one was taken afterwards.
//
// Bonus: false is also the fail-safe configuration. De-energised now means
// standby, so a reset, replug, upload or power loss drops the laser to standby
// instead of arming it.
bool READY_ON_NC = true;

int readyClosedLevel() { return READY_ON_NC ? COIL_RELEASED : COIL_ENERGIZED; }
int readyOpenLevel()   { return READY_ON_NC ? COIL_ENERGIZED : COIL_RELEASED; }

// Hold the contact open this long before closing it, so the closing edge is
// unambiguous. Well above the relay's ~10 ms mechanical operate time.
const unsigned long READY_EDGE_SETTLE_MS = 200;

// ---------------------------------------------------------------------------
// Fire Channels (pins 9 and 10)
// ---------------------------------------------------------------------------

// Which channels participate in a Fire.
bool fireCh1Enabled = true;
bool fireCh2Enabled = true;

// Polarity per channel.
//   false = normal:   contact OPEN at idle, CLOSES on fire   (relay on NO)
//   true  = inverted: contact CLOSED at idle, OPENS on fire  (changeover /
//                     relay on NC). This is hypothesis B - a changeover pedal
//                     needs one channel in each polarity, not both closing.
//
// WARNING: an inverted channel is ENERGIZED at idle. That is the state that
// previously made the Dornier complain continuously, so expect noise from the
// machine while testing this and do not leave it inverted by default.
bool fireCh1Invert = false;
bool fireCh2Invert = false;

int fireAssertLevel(bool invert) { return invert ? COIL_RELEASED : COIL_ENERGIZED; }
int fireIdleLevel(bool invert)   { return invert ? COIL_ENERGIZED : COIL_RELEASED; }

// Which channel changes state first, and the gap before the other follows.
// Dual-channel safety inputs often require one contact to lead the other.
int fireLeadChannel = 1;

const unsigned long GAP_TABLE_MS[] = {0, 25, 50, 100, 250, 500};
const int GAP_TABLE_COUNT = sizeof(GAP_TABLE_MS) / sizeof(GAP_TABLE_MS[0]);
int fireGapIndex = 0;

unsigned long fireGap_ms() { return GAP_TABLE_MS[fireGapIndex]; }

// After arming, wait this long with the fire contacts provably at idle before
// a Fire is allowed. If the machine samples the pedal as it enters READY, a
// too-early assertion is itself enough to trigger a footswitch complaint.
const unsigned long FIRE_ARM_DWELL_MS = 500;

// Minimum idle time between one Fire and the next, so any stuck-pedal
// detector always sees a clean release.
const unsigned long FIRE_RELEASE_DWELL_MS = 400;

// ---------------------------------------------------------------------------
// Laser State
// ---------------------------------------------------------------------------

bool laserEnabled = false;
bool laserReady = false;
bool laserFiring = false;

unsigned long readyAssertedAtMs = 0;
unsigned long fireIdleAtMs = 0;

// ---------------------------------------------------------------------------
// Function Prototypes
// ---------------------------------------------------------------------------

void setupLaserOutputs();
void driveFireChannelsToIdle();
void driveLaserOutputsToReleasedState();
void lockLaserSoftwareState();
void openReadyContact();
void closeReadyContactWithEdge();
void assertFireChannels();
void exerciseFireRelay(int pin, int channelLabel);
void pauseLaserFiring();
void stopLaserAndRelock();
void waitForDwell(unsigned long sinceMs, unsigned long requiredMs, const char* label);
bool readSerialLine(char inputLine[], size_t inputLineSize);
char getSingleLetterCommand(const char inputLine[]);
bool handleLaserCommand(char command);
void printReceivedInput(const char inputLine[]);
void printBuildBanner();
void printMenu();
void printLaserCommandHelp();
void printFireConfig();
void printReadyWiring();
void printLaserStatus();

// ---------------------------------------------------------------------------
// Laser Helpers
// ---------------------------------------------------------------------------

void setupLaserOutputs() {
  // On Teensy 4.x digitalWrite() before pinMode() sets the output data
  // register, so each pin drives the intended level the instant it becomes an
  // OUTPUT rather than glitching through the opposite state first.
  driveLaserOutputsToReleasedState();

  pinMode(relay_laser, OUTPUT);
  pinMode(fire1_laser, OUTPUT);
  pinMode(fire2_laser, OUTPUT);

  driveLaserOutputsToReleasedState();
  lockLaserSoftwareState();
}

void driveFireChannelsToIdle() {
  // Drive BOTH channels to their idle level regardless of the enable mask.
  // A channel that gets disabled mid-test must still be parked, not left
  // wherever it happened to be.
  digitalWrite(fire1_laser, fireIdleLevel(fireCh1Invert));
  digitalWrite(fire2_laser, fireIdleLevel(fireCh2Invert));
  laserFiring = false;
  fireIdleAtMs = millis();
}

void driveLaserOutputsToReleasedState() {
  // Safe state: fire channels at idle AND the ready contact OPEN (standby).
  //
  // The old build wrote LOW to pin 8 here unconditionally. On NC wiring that
  // CLOSES the ready contact - this one line is what armed the laser on [x].
  driveFireChannelsToIdle();
  digitalWrite(relay_laser, readyOpenLevel());
}

void lockLaserSoftwareState() {
  // Lock the command sequence. The user must send Enable [e] then Ready [r]
  // before Fire [f] is accepted again.
  laserEnabled = false;
  laserReady = false;
  laserFiring = false;
}

void openReadyContact() {
  digitalWrite(relay_laser, readyOpenLevel());
  Serial.print("  ready contact OPEN   (pin 8 -> ");
  Serial.print(readyOpenLevel() == HIGH ? "HIGH, coil ENERGIZED" : "LOW, coil released");
  Serial.println(")");
}

void closeReadyContactWithEdge() {
  // The Dornier arms on the open->closed TRANSITION, not on a static level.
  // Force open first so the closing edge is unambiguous regardless of what
  // state pin 8 was already sitting in.
  Serial.println("Ready sequence: forcing contact OPEN to guarantee a clean edge");
  digitalWrite(relay_laser, readyOpenLevel());
  delay(READY_EDGE_SETTLE_MS);

  digitalWrite(relay_laser, readyClosedLevel());
  readyAssertedAtMs = millis();
  Serial.print("  ready contact CLOSED and HELD (pin 8 -> ");
  Serial.print(readyClosedLevel() == HIGH ? "HIGH, coil ENERGIZED" : "LOW, coil released");
  Serial.println(")");
}

void waitForDwell(unsigned long sinceMs, unsigned long requiredMs, const char* label) {
  unsigned long elapsed = millis() - sinceMs;

  if (elapsed >= requiredMs) {
    return;
  }

  unsigned long remaining = requiredMs - elapsed;
  Serial.print("  waiting ");
  Serial.print(remaining);
  Serial.print(" ms for ");
  Serial.print(label);
  Serial.println(" dwell");
  delay(remaining);
}

void assertFireChannels() {
  // Move the selected channels from idle to asserted, in the configured order
  // with the configured gap. "Asserted" respects each channel's polarity, so
  // an inverted channel OPENS here while a normal one CLOSES.
  int  leadPin    = (fireLeadChannel == 1) ? fire1_laser : fire2_laser;
  int  trailPin   = (fireLeadChannel == 1) ? fire2_laser : fire1_laser;
  bool leadOn     = (fireLeadChannel == 1) ? fireCh1Enabled : fireCh2Enabled;
  bool trailOn    = (fireLeadChannel == 1) ? fireCh2Enabled : fireCh1Enabled;
  bool leadInv    = (fireLeadChannel == 1) ? fireCh1Invert : fireCh2Invert;
  bool trailInv   = (fireLeadChannel == 1) ? fireCh2Invert : fireCh1Invert;
  int  trailLabel = (fireLeadChannel == 1) ? 2 : 1;

  if (leadOn) {
    digitalWrite(leadPin, fireAssertLevel(leadInv));
    Serial.print("  fire channel ");
    Serial.print(fireLeadChannel);
    Serial.print(" (pin ");
    Serial.print(leadPin);
    Serial.print(") -> contact ");
    Serial.print(leadInv ? "OPEN" : "CLOSED");
    Serial.println("  [leading]");
  }

  if (leadOn && trailOn && fireGap_ms() > 0) {
    delay(fireGap_ms());
  }

  if (trailOn) {
    digitalWrite(trailPin, fireAssertLevel(trailInv));
    Serial.print("  fire channel ");
    Serial.print(trailLabel);
    Serial.print(" (pin ");
    Serial.print(trailPin);
    Serial.print(") -> contact ");
    Serial.print(trailInv ? "OPEN" : "CLOSED");
    Serial.print("  [trailing by ");
    Serial.print(leadOn ? fireGap_ms() : 0);
    Serial.println(" ms]");
  }
}

void exerciseFireRelay(int pin, int channelLabel) {
  // Bench test for ONE fire relay in isolation.
  //
  // Purpose: pin 10 has never produced an observable effect on the Dornier in
  // any test, while pin 9 reliably does. That is a hardware question - is the
  // pin 10 channel actually switching, and does its switching reach anything?
  // This drives the coil directly, ignoring the invert setting, so the click
  // is audible and the output terminals can be metered.
  //
  // SAFETY: the ready contact is forced OPEN for the whole test, so the
  // machine is in standby and nothing can fire no matter what these contacts
  // do. The other fire channel is parked at idle.
  digitalWrite(relay_laser, readyOpenLevel());
  laserReady = false;
  driveFireChannelsToIdle();

  Serial.println("--- FIRE RELAY BENCH TEST ---");
  Serial.print("Exercising fire channel ");
  Serial.print(channelLabel);
  Serial.print(" (pin ");
  Serial.print(pin);
  Serial.println(") in isolation.");
  Serial.println("Ready contact is forced OPEN - the laser is in standby and");
  Serial.println("cannot fire during this test.");
  Serial.println("LISTEN for the relay click. METER continuity across that");
  Serial.println("channel's output terminals. Compare against the other channel.");

  for (int cycle = 1; cycle <= 5; cycle++) {
    Serial.print("  cycle ");
    Serial.print(cycle);
    Serial.println("/5: coil ENERGIZED");
    digitalWrite(pin, COIL_ENERGIZED);
    delay(1000);

    Serial.println("           coil released");
    digitalWrite(pin, COIL_RELEASED);
    delay(1000);
  }

  driveFireChannelsToIdle();

  Serial.println("Test finished. Channel returned to idle.");
  Serial.println("No click on this channel -> dead board channel, missing");
  Serial.println("  jumper, or no coil power. Fix that before any more firmware.");
  Serial.println("Clicks but the Dornier never reacts -> the contact is landed");
  Serial.println("  on the wrong terminals of the Steute connector.");
  Serial.println("-----------------------------");
}

void pauseLaserFiring() {
  // Return both fire channels to idle. Does not clear laserEnabled/laserReady.
  driveFireChannelsToIdle();
}

void stopLaserAndRelock() {
  // Release the fire channels first, then open the ready contact.
  // Opening the contact IS the "clear ready" action - nothing is pulsed.
  pauseLaserFiring();
  driveLaserOutputsToReleasedState();
  lockLaserSoftwareState();
}

// ---------------------------------------------------------------------------
// Serial Input Helpers
// ---------------------------------------------------------------------------

bool readSerialLine(char inputLine[], size_t inputLineSize) {
  size_t inputLength = Serial.readBytesUntil('\n', inputLine, inputLineSize - 1);

  // If Serial Monitor is set to "Both NL & CR", readBytesUntil('\n') leaves
  // the carriage return at the end. Remove it so the echo prints cleanly and
  // parsing behaves the same for every line-ending mode.
  if (inputLength > 0 && inputLine[inputLength - 1] == '\r') {
    inputLength--;
  }

  inputLine[inputLength] = '\0';

  // Ignore blank lines.
  for (size_t i = 0; i < inputLength; i++) {
    if (inputLine[i] != ' ' && inputLine[i] != '\t') {
      return true;
    }
  }

  return false;
}

char getSingleLetterCommand(const char inputLine[]) {
  int inputStart = 0;

  while (inputLine[inputStart] == ' ' || inputLine[inputStart] == '\t') {
    inputStart++;
  }

  char command = inputLine[inputStart];

  if (command == '\0') {
    return '\0';
  }

  int inputEnd = inputStart + 1;

  while (inputLine[inputEnd] == ' ' || inputLine[inputEnd] == '\t') {
    inputEnd++;
  }

  // One-character commands only.
  if (inputLine[inputEnd] != '\0') {
    return '\0';
  }

  if (command >= 'A' && command <= 'Z') {
    command = command + 32;
  }

  return command;
}

void printReceivedInput(const char inputLine[]) {
  Serial.print("Serial Monitor input received: [");
  Serial.print(inputLine);
  Serial.println("]");
}

// ---------------------------------------------------------------------------
// Laser Command Handler
// ---------------------------------------------------------------------------

bool handleLaserCommand(char command) {
  if (command == '\0') {
    Serial.println("Wrong Format");
    Serial.println("Commands are one character only.");

    if (laserFiring) {
      Serial.println("Invalid input received while firing. Emergency stop triggered.");
      stopLaserAndRelock();
      Serial.println("All laser outputs are OFF. Laser commands are locked.");
    } else {
      printLaserCommandHelp();
    }

    return false;
  }

  Serial.print("Laser command input: ");
  Serial.println(command);

  // -------------------------------------------------------------------------
  // e: enable software command sequence
  // -------------------------------------------------------------------------
  if (command == 'e') {
    if (laserFiring) {
      Serial.println("Enable [e] is not allowed while firing. Emergency stop triggered.");
      stopLaserAndRelock();
      Serial.println("All laser outputs are OFF. Laser commands are locked.");
      return true;
    }

    if (laserEnabled) {
      Serial.println("Enable [e] ignored: laser commands are already unlocked.");
      return true;
    }

    driveLaserOutputsToReleasedState();
    laserEnabled = true;
    laserReady = false;

    Serial.println("Laser command: Enable [e]");
    Serial.println("Laser commands are unlocked. Next type Ready [r] before Fire [f].");
    return true;
  }

  // -------------------------------------------------------------------------
  // r: ready - open->settle->close edge, then hold
  // -------------------------------------------------------------------------
  if (command == 'r') {
    if (laserFiring) {
      Serial.println("Ready [r] is not allowed while firing. Emergency stop triggered.");
      stopLaserAndRelock();
      Serial.println("All laser outputs are OFF. Laser commands are locked.");
      return true;
    }

    if (!laserEnabled) {
      Serial.println("Ready blocked: type Enable [e] first.");
      printLaserCommandHelp();
      return true;
    }

    if (laserReady) {
      Serial.println("Ready [r] ignored: laser is already ready.");
      return true;
    }

    // Park the fire channels only - closeReadyContactWithEdge() owns pin 8.
    // The fire contacts must be provably at idle before the machine arms, or
    // it may latch a footswitch complaint at the moment it enters READY.
    pauseLaserFiring();

    Serial.println("Laser command: Ready [r]");
    closeReadyContactWithEdge();
    laserReady = true;

    // This flag is SOFTWARE STATE ONLY. Nothing here reads back from the
    // Dornier, so this sketch cannot know whether the machine actually armed.
    // Say so, rather than printing a confident "READY" that has repeatedly
    // been believed over the machine's own screen.
    Serial.println("Software now believes the laser is ready - this is NOT confirmation.");
    Serial.println(">>> LOOK AT THE DORNIER SCREEN. Does it read READY? <<<");
    return true;
  }

  // -------------------------------------------------------------------------
  // f: fire
  // -------------------------------------------------------------------------
  if (command == 'f') {
    if (!laserEnabled || !laserReady) {
      Serial.println("Fire blocked: type Enable [e], then Ready [r], then Fire [f].");
      printLaserCommandHelp();
      return true;
    }

    if (laserFiring) {
      Serial.println("Fire [f] ignored: laser is already firing.");
      return true;
    }

    if (!fireCh1Enabled && !fireCh2Enabled) {
      Serial.println("Fire blocked: both fire channels are disabled. Send [1] or [2].");
      return true;
    }

    Serial.println("Laser command: Fire [f]");
    printFireConfig();

    // Give the machine a clean, provably-idle footswitch window before
    // asserting. Both dwells are no-ops once enough time has already passed.
    waitForDwell(readyAssertedAtMs, FIRE_ARM_DWELL_MS, "post-arm");
    waitForDwell(fireIdleAtMs, FIRE_RELEASE_DWELL_MS, "post-release");

    assertFireChannels();
    laserFiring = true;

    Serial.println("Fire channels asserted and HELD. Send Pause [p] to release.");
    Serial.println("Still says \"release footswitch fully\"? Send [p], then try the");
    Serial.println("next row of the test matrix printed at boot.");
    return true;
  }

  // -------------------------------------------------------------------------
  // p: pause firing
  // -------------------------------------------------------------------------
  if (command == 'p') {
    Serial.println("Laser command: Pause [p]");
    pauseLaserFiring();
    Serial.println("Both fire channels are back at idle. Laser remains enabled and ready.");
    return true;
  }

  // -------------------------------------------------------------------------
  // s: standby - opens the ready contact
  // -------------------------------------------------------------------------
  if (command == 's') {
    if (!laserEnabled) {
      Serial.println("Standby blocked: type Enable [e] first.");
      printLaserCommandHelp();
      return true;
    }

    Serial.println("Laser command: Standby [s]");
    pauseLaserFiring();

    // Always drive the contact open, even if the software did not think the
    // laser was ready. If the two disagree, the safe move is to open.
    openReadyContact();

    laserReady = false;
    Serial.println("Standby finished. Type Ready [r] before Fire [f].");
    return true;
  }

  // -------------------------------------------------------------------------
  // x: stop and relock
  // -------------------------------------------------------------------------
  if (command == 'x') {
    Serial.println("Laser command: Stop [x]");
    stopLaserAndRelock();
    Serial.println("All outputs at idle. Ready contact is OPEN. Commands locked.");
    return true;
  }

  // -------------------------------------------------------------------------
  // 1 / 2: enable or disable a fire channel
  // -------------------------------------------------------------------------
  if (command == '1' || command == '2') {
    if (laserFiring) {
      Serial.println("Channel toggle refused while firing. Send Pause [p] first.");
      return true;
    }

    if (command == '1') {
      fireCh1Enabled = !fireCh1Enabled;
    } else {
      fireCh2Enabled = !fireCh2Enabled;
    }

    pauseLaserFiring();
    printFireConfig();
    return true;
  }

  // -------------------------------------------------------------------------
  // 3 / 4: invert a fire channel's polarity (changeover-pedal hypothesis)
  // -------------------------------------------------------------------------
  if (command == '3' || command == '4') {
    if (laserFiring) {
      Serial.println("Polarity toggle refused while firing. Send Pause [p] first.");
      return true;
    }

    if (command == '3') {
      fireCh1Invert = !fireCh1Invert;
    } else {
      fireCh2Invert = !fireCh2Invert;
    }

    // Re-park both channels under the NEW polarity, so idle really is idle.
    pauseLaserFiring();

    Serial.println("Channel polarity changed. Both channels re-parked at idle.");
    if (fireCh1Invert || fireCh2Invert) {
      Serial.println("NOTE: an inverted channel is ENERGIZED at idle. If the Dornier");
      Serial.println("starts complaining continuously with no Fire sent, that is this.");
    }
    printFireConfig();
    return true;
  }

  // -------------------------------------------------------------------------
  // o: swap which channel leads
  // -------------------------------------------------------------------------
  if (command == 'o') {
    if (laserFiring) {
      Serial.println("Lead swap refused while firing. Send Pause [p] first.");
      return true;
    }

    fireLeadChannel = (fireLeadChannel == 1) ? 2 : 1;
    printFireConfig();
    return true;
  }

  // -------------------------------------------------------------------------
  // g: step the inter-channel gap
  // -------------------------------------------------------------------------
  if (command == 'g') {
    fireGapIndex = (fireGapIndex + 1) % GAP_TABLE_COUNT;
    Serial.print("Inter-channel gap: ");
    Serial.print(fireGap_ms());
    Serial.println(" ms");
    return true;
  }

  // -------------------------------------------------------------------------
  // t / y: exercise one fire relay in isolation
  // -------------------------------------------------------------------------
  if (command == 't' || command == 'y') {
    if (laserFiring) {
      Serial.println("Bench test refused while firing. Send Pause [p] first.");
      return true;
    }

    if (command == 't') {
      exerciseFireRelay(fire1_laser, 1);
    } else {
      exerciseFireRelay(fire2_laser, 2);
    }

    return true;
  }

  // -------------------------------------------------------------------------
  // ?: status
  // -------------------------------------------------------------------------
  if (command == '?') {
    printBuildBanner();
    printMenu();
    printReadyWiring();
    printFireConfig();
    printLaserStatus();
    return true;
  }

  // -------------------------------------------------------------------------
  // Unknown command
  // -------------------------------------------------------------------------
  Serial.println("Unknown command.");

  if (laserFiring) {
    Serial.println("Unknown command received while firing. Emergency stop triggered.");
    stopLaserAndRelock();
    Serial.println("All laser outputs are OFF. Laser commands are locked.");
    return false;
  }

  printLaserCommandHelp();
  return false;
}

// ---------------------------------------------------------------------------
// Serial Printing
// ---------------------------------------------------------------------------

void printBuildBanner() {
  Serial.println("===========================================================");
  Serial.print("  BUILD: ");
  Serial.println(BUILD_NAME);
  Serial.print("  ");
  Serial.println(BUILD_NOTE);
  Serial.println("  No banner after a reset = the board is running a DIFFERENT");
  Serial.println("  sketch, and no test result from it means anything.");
  Serial.println("===========================================================");
}

void printMenu() {
  Serial.println("--- DORNIER LASER ACTIVATION SYSTEM ---");
  printLaserCommandHelp();
  Serial.println("---------------------------------------");
}

void printLaserCommandHelp() {
  Serial.println("LASER: [e] Enable | [r] Ready | [f] Fire | [p] Pause | [s] Standby | [x] Stop");
  Serial.println("FIRE:  [1]/[2] channel on-off | [3]/[4] invert polarity");
  Serial.println("       [o] swap lead | [g] gap ms | [?] status");
  Serial.println("BENCH: [t] exercise pin 9 relay | [y] exercise pin 10 relay");
}

void printReadyWiring() {
  Serial.println("  --- ready channel (pin 8) ---");
  Serial.print("  landed on     : ");
  Serial.println(READY_ON_NC ? "NC (contact CLOSED when coil released)"
                             : "NO (contact OPEN when coil released)");
  Serial.print("  close contact : pin 8 -> ");
  Serial.println(readyClosedLevel() == HIGH ? "HIGH" : "LOW");
  Serial.print("  open contact  : pin 8 -> ");
  Serial.println(readyOpenLevel() == HIGH ? "HIGH" : "LOW");
  Serial.println("  -----------------------------");
}

void printFireConfig() {
  Serial.println("  --- fire channels ---");
  Serial.print("  ch1 (pin 9)  : ");
  Serial.print(fireCh1Enabled ? "ENABLED " : "disabled");
  Serial.print(fireCh1Invert ? "  INVERTED (closed at idle, opens on fire)"
                             : "  normal (open at idle, closes on fire)");
  Serial.println();
  Serial.print("  ch2 (pin 10) : ");
  Serial.print(fireCh2Enabled ? "ENABLED " : "disabled");
  Serial.print(fireCh2Invert ? "  INVERTED (closed at idle, opens on fire)"
                             : "  normal (open at idle, closes on fire)");
  Serial.println();
  Serial.print("  leads        : channel ");
  Serial.println(fireLeadChannel);
  Serial.print("  gap          : ");
  Serial.print(fireGap_ms());
  Serial.println(" ms");
  Serial.println("  ---------------------");
}

void printLaserStatus() {
  Serial.print("Laser enabled/ready/firing: ");
  Serial.print(laserEnabled);
  Serial.print("/");
  Serial.print(laserReady);
  Serial.print("/");
  Serial.println(laserFiring);

  Serial.print("Pin levels 8/9/10: ");
  Serial.print(digitalRead(relay_laser));
  Serial.print("/");
  Serial.print(digitalRead(fire1_laser));
  Serial.print("/");
  Serial.println(digitalRead(fire2_laser));
}

// ---------------------------------------------------------------------------
// Arduino Setup
// ---------------------------------------------------------------------------

void laserSetup() {
  setupLaserOutputs();

  Serial.begin(115200);
  Serial.setTimeout(500);
  delay(2000);

  printBuildBanner();
  printMenu();
  printReadyWiring();
  printFireConfig();

  if (READY_ON_NC) {
    Serial.println("!! FAIL-SAFE WARNING: pin 8 is on the relay's NC terminal.");
    Serial.println("!! Standby needs the coil ENERGIZED, so a reset, replug, upload,");
    Serial.println("!! loose jumper, or relay-supply loss ARMS the laser unattended.");
    Serial.println("!! Fix in hardware: move pin 8 from NC to NO, then set");
    Serial.println("!! READY_ON_NC = false. Do not leave this rig unattended.");
  } else {
    Serial.println("Fail-safe: pin 8 treated as NO. Coil released = contact open =");
    Serial.println("standby, so a reset or power loss drops the laser to standby.");
    Serial.println("This is the correct and safe configuration.");
  }

  Serial.println("STATUS: Fire is working. Ready is the open item.");
  Serial.println("  Ready does not arm? Send [w] to flip the pin 8 sense at");
  Serial.println("  runtime, then [x] [e] [r] and watch the Dornier screen.");
  Serial.println("  [w] is runtime only - it resets on every boot. Tell me which");
  Serial.println("  way works and I will make it the permanent default.");
  printLaserStatus();
}

// ---------------------------------------------------------------------------
// Arduino Main Loop
// ---------------------------------------------------------------------------




// ===========================================================================
// Merged Command Dispatcher
// ===========================================================================

// Single letters owned by the laser sketch. 'h' is deliberately absent: it is
// the motion sketch's home shortcut, and the two alphabets must stay disjoint.
static bool isLaserCommand(char command) {
  switch (command) {
    case 'e': case 'r': case 'f': case 'p': case 's': case 'x':
    case '1': case '2': case '3': case '4':
    case 'o': case 'g': case 't': case 'y': case 'w': case '?':
      return true;
    default:
      return false;
  }
}

static bool readDispatchLine(char inputLine[], size_t size) {
  size_t length = Serial.readBytesUntil('\n', inputLine, size - 1);

  if (length > 0 && inputLine[length - 1] == '\r') {
    length--;
  }
  inputLine[length] = '\0';

  for (size_t i = 0; i < length; i++) {
    if (inputLine[i] != ' ' && inputLine[i] != '\t') {
      return true;
    }
  }
  return false;  // blank line
}

// The original motion loop printed its prompt once because it then blocked on
// "while (Serial.available() == 0) {}". The merged loop must not block -- a
// laser command has to be servicable at any time -- so the prompt is instead
// gated on a flag and printed exactly once per handled command.
static bool promptPending = true;

void setup() {
  // Laser first and deliberately: setupLaserOutputs() parks the relays in their
  // safe state, and that must happen before anything else can take time.
  laserSetup();
  motionSetup();

  Serial.println();
  Serial.println("=== COMBINED MOTION + LASER BUILD ===");
  Serial.println("Motion: three numbers, or home/h");
  Serial.println("Laser : e r f p s x 1 2 3 4 o g t y w ?");
  Serial.println("Send q for terse output when driving from a host program.");
  promptPending = true;
}

void loop() {
  if (promptPending) {
    printCommandPrompt();
    promptPending = false;
  }

  if (Serial.available() <= 0) {
    return;
  }

  char inputLine[64];
  if (!readDispatchLine(inputLine, sizeof(inputLine))) {
    return;  // blank line, nothing consumed, no new prompt owed
  }

  char single = getSingleLetterCommand(inputLine);

  if (single == 'q') {
    terseOutput = !terseOutput;
    Serial.print("Terse output: ");
    Serial.println(terseOutput ? "ON" : "OFF");
    promptPending = true;
    return;
  }

  // A bare digit is ambiguous: it is a laser channel/polarity command, and it
  // is also not a valid motion command (motion always needs three numbers), so
  // it is routed to the laser. Hosts send all three numbers and never hit this.
  // v<microseconds>: set the STEP pulse half-period at runtime.
  // The sketch has no acceleration ramp, so this is the rate the motor must
  // start at from a standstill -- lower it too far and the stepper stalls
  // instead of turning. Tune by feel: halve it, test, repeat until it slips,
  // then back off.
  if (inputLine[0] == 'v' || inputLine[0] == 'V') {
    int requested = atoi(inputLine + 1);

    if (requested >= 40 && requested <= 5000) {
      stepDelay_us = (unsigned int)requested;
      Serial.print("Step delay: ");
      Serial.print(stepDelay_us);
      Serial.print(" us  ->  ");
      Serial.print(1000000.0f / (2.0f * stepDelay_us), 0);
      Serial.print(" pulses/s  ->  ");
      Serial.print((1000000.0f / (2.0f * stepDelay_us)) * linearMMPerRev / linearPulsesPerRev, 2);
      Serial.println(" mm/s max");
    } else {
      Serial.println("Step delay must be 40 to 5000 us");
    }

    promptPending = true;
    return;
  }

  if (single != '\0' && isLaserCommand(single)) {
    if (!terseOutput) {
      printReceivedInput(inputLine);
    }
    handleLaserCommand(single);
    printLaserStatus();
    promptPending = true;
    return;
  }

  // Anything else belongs to the motion sketch.
  if (!parseMovementLine(inputLine)) {
    Serial.println("Wrong Format");
    promptPending = true;
    return;
  }

  if (!calculateAllTargets()) {
    promptPending = true;
    return;
  }

  moveAllAxesTogether();
  promptPending = true;
}
