/// Motion Velocity Server  -  Teensy 4.1  -  GENERATED FILE, DO NOT EDIT BY HAND
/*
  Generated by python/scripts/build_velocity_firmware.py from:
    firmware/src/velocity_motion_core.inc          (motion, hand-maintained)
    shootingyesready_inoF-1/shootingyesready_inoF-1.ino   (laser, VERBATIM)

  Edit those and re-run the build script. Editing this file means the next
  build discards your change.

  THE LASER CODE HERE IS NOT A REIMPLEMENTATION.
    An earlier version of this sketch rewrote the laser by hand and lost the arm
    and release dwell timers, the fire-channel lead order and gap, and the
    per-relay bench test. The laser worked before that rewrite and stopped
    afterwards. It is now spliced in from the original sketch unchanged, so its
    behaviour is identical to the build it was working on.

  MOTION
    Velocity mode: the host sets a target speed per axis and the firmware ramps
    toward it, stepping continuously. Nothing blocks, so motion is smooth,
    proportional to stick deflection, and stoppable inside a millisecond.
    Position is estimated by counting STEP pulses; the encoders are not read.
    Start the carriage at mechanical home -- that becomes 0.00 mm.

  COMMANDS
    L<mm/s>   target linear velocity        S    stop all motion now
    R<deg/s>  target rotation velocity      Z    zero the position estimates
    F<deg>    absolute flexion tip angle    H    home (abortable with S)
    T<ms>     telemetry period              D<deg> flexion re-command deadband
    A<sec>    flexion lead time             P<mask> fire polarity, bit0=ch1 bit1=ch2
    ?         status

    e r f p s x 1 2 3 4 o g t y w   laser, exactly as the original sketch

  !!! LASER FAIL-SAFE - LIVE !!!
    READY_ON_NC is true: pin 8 is on the relay's NC terminal, so the ready
    contact is CLOSED (laser ARMED) whenever the coil is de-energised. A reset,
    replug, upload, loose jumper or loss of relay supply arms the laser with
    nobody commanding it. De-energise the relay supply before flashing.
    Fix in hardware: move pin 8 to NO, then set READY_ON_NC = false.
*/

// ==========================================================================
// Laser, spliced verbatim from shootingyesready_inoF-1.ino
// ==========================================================================


// ---------------------------------------------------------------------------
// Build Identity
// ---------------------------------------------------------------------------

// Printed at boot and on [?]. If you reset the Teensy and do not see this
// banner, the board is running a DIFFERENT sketch and nothing in this file is
// in effect. Check the banner before trusting any test result.
const char* BUILD_NAME = "LASER-V5.2";
const char* BUILD_NOTE = "pin8 NO + edge-armed; fire confirmed working; [w] flips ready sense";

// ---------------------------------------------------------------------------
// Laser Pin Assignments
// ---------------------------------------------------------------------------

const int relay_laser = 8;
const int fire1_laser = 9;
const int fire2_laser = 10;

// ---------------------------------------------------------------------------
// Relay Board Electrical Facts
// ---------------------------------------------------------------------------

// All three boards are high-level-trigger type:
//   HIGH = coil energizes -> NO closes, NC opens
//   LOW  = coil releases  -> NO opens,  NC closes
const int COIL_ENERGIZED = HIGH;
const int COIL_RELEASED  = LOW;

// ---------------------------------------------------------------------------
// Ready Channel (pin 8)
// ---------------------------------------------------------------------------

// true  = pin 8 is on the NC terminal (contact closed when the coil releases)
// false = pin 8 is on the NO terminal (contact open when the coil releases)
//
// CHANGED TO false IN V5.2. Fire started working after an undocumented
// hardware change, and Ready stopped working in the same moment. Ready had
// been correct on NC, so whatever moved also flipped pin 8's sense - the
// wire is now behaving as NO. This is the matching software change.
//
// If Ready still does not arm, this assumption is wrong: send [w] to flip it
// back at runtime (no reflash) and tell me, because then the hardware change
// did something other than move pin 8.
// false as of 2026-09-03, decided on clean evidence rather than inference.
//
// Symptom: with fire working correctly, STANDBY and STOP both armed the machine
// while READY did not -- i.e. it armed on the edge our "open" produces. That is
// an inverted ready sense, and it is Bug 1's signature exactly.
//
// Earlier attempts to flip this were made while two host-side bugs were active
// (the motion driver was draining the laser's serial replies, and arm() was
// driving the fire relays), so every observation before those were fixed was
// unreliable. This one was taken afterwards.
//
// Bonus: false is also the fail-safe configuration. De-energised now means
// standby, so a reset, replug, upload or power loss drops the laser to standby
// instead of arming it.
bool READY_ON_NC = true;

int readyClosedLevel() { return READY_ON_NC ? COIL_RELEASED : COIL_ENERGIZED; }
int readyOpenLevel()   { return READY_ON_NC ? COIL_ENERGIZED : COIL_RELEASED; }

// Hold the contact open this long before closing it, so the closing edge is
// unambiguous. Well above the relay's ~10 ms mechanical operate time.
const unsigned long READY_EDGE_SETTLE_MS = 200;

// ---------------------------------------------------------------------------
// Fire Channels (pins 9 and 10)
// ---------------------------------------------------------------------------

// Which channels participate in a Fire.
bool fireCh1Enabled = true;
bool fireCh2Enabled = true;

// Polarity per channel.
//   false = normal:   contact OPEN at idle, CLOSES on fire   (relay on NO)
//   true  = inverted: contact CLOSED at idle, OPENS on fire  (changeover /
//                     relay on NC). This is hypothesis B - a changeover pedal
//                     needs one channel in each polarity, not both closing.
//
// WARNING: an inverted channel is ENERGIZED at idle. That is the state that
// previously made the Dornier complain continuously, so expect noise from the
// machine while testing this and do not leave it inverted by default.
bool fireCh1Invert = false;
bool fireCh2Invert = false;

int fireAssertLevel(bool invert) { return invert ? COIL_RELEASED : COIL_ENERGIZED; }
int fireIdleLevel(bool invert)   { return invert ? COIL_ENERGIZED : COIL_RELEASED; }

// Which channel changes state first, and the gap before the other follows.
// Dual-channel safety inputs often require one contact to lead the other.
int fireLeadChannel = 1;

const unsigned long GAP_TABLE_MS[] = {0, 25, 50, 100, 250, 500};
const int GAP_TABLE_COUNT = sizeof(GAP_TABLE_MS) / sizeof(GAP_TABLE_MS[0]);
int fireGapIndex = 0;

unsigned long fireGap_ms() { return GAP_TABLE_MS[fireGapIndex]; }

// After arming, wait this long with the fire contacts provably at idle before
// a Fire is allowed. If the machine samples the pedal as it enters READY, a
// too-early assertion is itself enough to trigger a footswitch complaint.
const unsigned long FIRE_ARM_DWELL_MS = 500;

// Minimum idle time between one Fire and the next, so any stuck-pedal
// detector always sees a clean release.
const unsigned long FIRE_RELEASE_DWELL_MS = 400;

// ---------------------------------------------------------------------------
// Laser State
// ---------------------------------------------------------------------------

bool laserEnabled = false;
bool laserReady = false;
bool laserFiring = false;

unsigned long readyAssertedAtMs = 0;
unsigned long fireIdleAtMs = 0;

// ---------------------------------------------------------------------------
// Function Prototypes
// ---------------------------------------------------------------------------

void setupLaserOutputs();
void driveFireChannelsToIdle();
void driveLaserOutputsToReleasedState();
void lockLaserSoftwareState();
void openReadyContact();
void closeReadyContactWithEdge();
void assertFireChannels();
void exerciseFireRelay(int pin, int channelLabel);
void pauseLaserFiring();
void stopLaserAndRelock();
void waitForDwell(unsigned long sinceMs, unsigned long requiredMs, const char* label);
bool readSerialLine(char inputLine[], size_t inputLineSize);
char getSingleLetterCommand(const char inputLine[]);
bool handleLaserCommand(char command);
void printReceivedInput(const char inputLine[]);
void printBuildBanner();
void printMenu();
void printLaserCommandHelp();
void printFireConfig();
void printReadyWiring();
void printLaserStatus();

// ---------------------------------------------------------------------------
// Laser Helpers
// ---------------------------------------------------------------------------

void setupLaserOutputs() {
  // On Teensy 4.x digitalWrite() before pinMode() sets the output data
  // register, so each pin drives the intended level the instant it becomes an
  // OUTPUT rather than glitching through the opposite state first.
  driveLaserOutputsToReleasedState();

  pinMode(relay_laser, OUTPUT);
  pinMode(fire1_laser, OUTPUT);
  pinMode(fire2_laser, OUTPUT);

  driveLaserOutputsToReleasedState();
  lockLaserSoftwareState();
}

void driveFireChannelsToIdle() {
  // Drive BOTH channels to their idle level regardless of the enable mask.
  // A channel that gets disabled mid-test must still be parked, not left
  // wherever it happened to be.
  digitalWrite(fire1_laser, fireIdleLevel(fireCh1Invert));
  digitalWrite(fire2_laser, fireIdleLevel(fireCh2Invert));
  laserFiring = false;
  fireIdleAtMs = millis();
}

void driveLaserOutputsToReleasedState() {
  // Safe state: fire channels at idle AND the ready contact OPEN (standby).
  //
  // The old build wrote LOW to pin 8 here unconditionally. On NC wiring that
  // CLOSES the ready contact - this one line is what armed the laser on [x].
  driveFireChannelsToIdle();
  digitalWrite(relay_laser, readyOpenLevel());
}

void lockLaserSoftwareState() {
  // Lock the command sequence. The user must send Enable [e] then Ready [r]
  // before Fire [f] is accepted again.
  laserEnabled = false;
  laserReady = false;
  laserFiring = false;
}

void openReadyContact() {
  digitalWrite(relay_laser, readyOpenLevel());
  Serial.print("  ready contact OPEN   (pin 8 -> ");
  Serial.print(readyOpenLevel() == HIGH ? "HIGH, coil ENERGIZED" : "LOW, coil released");
  Serial.println(")");
}

void closeReadyContactWithEdge() {
  // The Dornier arms on the open->closed TRANSITION, not on a static level.
  // Force open first so the closing edge is unambiguous regardless of what
  // state pin 8 was already sitting in.
  Serial.println("Ready sequence: forcing contact OPEN to guarantee a clean edge");
  digitalWrite(relay_laser, readyOpenLevel());
  delay(READY_EDGE_SETTLE_MS);

  digitalWrite(relay_laser, readyClosedLevel());
  readyAssertedAtMs = millis();
  Serial.print("  ready contact CLOSED and HELD (pin 8 -> ");
  Serial.print(readyClosedLevel() == HIGH ? "HIGH, coil ENERGIZED" : "LOW, coil released");
  Serial.println(")");
}

void waitForDwell(unsigned long sinceMs, unsigned long requiredMs, const char* label) {
  unsigned long elapsed = millis() - sinceMs;

  if (elapsed >= requiredMs) {
    return;
  }

  unsigned long remaining = requiredMs - elapsed;
  Serial.print("  waiting ");
  Serial.print(remaining);
  Serial.print(" ms for ");
  Serial.print(label);
  Serial.println(" dwell");
  delay(remaining);
}

void assertFireChannels() {
  // Move the selected channels from idle to asserted, in the configured order
  // with the configured gap. "Asserted" respects each channel's polarity, so
  // an inverted channel OPENS here while a normal one CLOSES.
  int  leadPin    = (fireLeadChannel == 1) ? fire1_laser : fire2_laser;
  int  trailPin   = (fireLeadChannel == 1) ? fire2_laser : fire1_laser;
  bool leadOn     = (fireLeadChannel == 1) ? fireCh1Enabled : fireCh2Enabled;
  bool trailOn    = (fireLeadChannel == 1) ? fireCh2Enabled : fireCh1Enabled;
  bool leadInv    = (fireLeadChannel == 1) ? fireCh1Invert : fireCh2Invert;
  bool trailInv   = (fireLeadChannel == 1) ? fireCh2Invert : fireCh1Invert;
  int  trailLabel = (fireLeadChannel == 1) ? 2 : 1;

  if (leadOn) {
    digitalWrite(leadPin, fireAssertLevel(leadInv));
    Serial.print("  fire channel ");
    Serial.print(fireLeadChannel);
    Serial.print(" (pin ");
    Serial.print(leadPin);
    Serial.print(") -> contact ");
    Serial.print(leadInv ? "OPEN" : "CLOSED");
    Serial.println("  [leading]");
  }

  if (leadOn && trailOn && fireGap_ms() > 0) {
    delay(fireGap_ms());
  }

  if (trailOn) {
    digitalWrite(trailPin, fireAssertLevel(trailInv));
    Serial.print("  fire channel ");
    Serial.print(trailLabel);
    Serial.print(" (pin ");
    Serial.print(trailPin);
    Serial.print(") -> contact ");
    Serial.print(trailInv ? "OPEN" : "CLOSED");
    Serial.print("  [trailing by ");
    Serial.print(leadOn ? fireGap_ms() : 0);
    Serial.println(" ms]");
  }
}

void exerciseFireRelay(int pin, int channelLabel) {
  // Bench test for ONE fire relay in isolation.
  //
  // Purpose: pin 10 has never produced an observable effect on the Dornier in
  // any test, while pin 9 reliably does. That is a hardware question - is the
  // pin 10 channel actually switching, and does its switching reach anything?
  // This drives the coil directly, ignoring the invert setting, so the click
  // is audible and the output terminals can be metered.
  //
  // SAFETY: the ready contact is forced OPEN for the whole test, so the
  // machine is in standby and nothing can fire no matter what these contacts
  // do. The other fire channel is parked at idle.
  digitalWrite(relay_laser, readyOpenLevel());
  laserReady = false;
  driveFireChannelsToIdle();

  Serial.println("--- FIRE RELAY BENCH TEST ---");
  Serial.print("Exercising fire channel ");
  Serial.print(channelLabel);
  Serial.print(" (pin ");
  Serial.print(pin);
  Serial.println(") in isolation.");
  Serial.println("Ready contact is forced OPEN - the laser is in standby and");
  Serial.println("cannot fire during this test.");
  Serial.println("LISTEN for the relay click. METER continuity across that");
  Serial.println("channel's output terminals. Compare against the other channel.");

  for (int cycle = 1; cycle <= 5; cycle++) {
    Serial.print("  cycle ");
    Serial.print(cycle);
    Serial.println("/5: coil ENERGIZED");
    digitalWrite(pin, COIL_ENERGIZED);
    delay(1000);

    Serial.println("           coil released");
    digitalWrite(pin, COIL_RELEASED);
    delay(1000);
  }

  driveFireChannelsToIdle();

  Serial.println("Test finished. Channel returned to idle.");
  Serial.println("No click on this channel -> dead board channel, missing");
  Serial.println("  jumper, or no coil power. Fix that before any more firmware.");
  Serial.println("Clicks but the Dornier never reacts -> the contact is landed");
  Serial.println("  on the wrong terminals of the Steute connector.");
  Serial.println("-----------------------------");
}

void pauseLaserFiring() {
  // Return both fire channels to idle. Does not clear laserEnabled/laserReady.
  driveFireChannelsToIdle();
}

void stopLaserAndRelock() {
  // Release the fire channels first, then open the ready contact.
  // Opening the contact IS the "clear ready" action - nothing is pulsed.
  pauseLaserFiring();
  driveLaserOutputsToReleasedState();
  lockLaserSoftwareState();
}

// ---------------------------------------------------------------------------
// Serial Input Helpers
// ---------------------------------------------------------------------------

bool readSerialLine(char inputLine[], size_t inputLineSize) {
  size_t inputLength = Serial.readBytesUntil('\n', inputLine, inputLineSize - 1);

  // If Serial Monitor is set to "Both NL & CR", readBytesUntil('\n') leaves
  // the carriage return at the end. Remove it so the echo prints cleanly and
  // parsing behaves the same for every line-ending mode.
  if (inputLength > 0 && inputLine[inputLength - 1] == '\r') {
    inputLength--;
  }

  inputLine[inputLength] = '\0';

  // Ignore blank lines.
  for (size_t i = 0; i < inputLength; i++) {
    if (inputLine[i] != ' ' && inputLine[i] != '\t') {
      return true;
    }
  }

  return false;
}

char getSingleLetterCommand(const char inputLine[]) {
  int inputStart = 0;

  while (inputLine[inputStart] == ' ' || inputLine[inputStart] == '\t') {
    inputStart++;
  }

  char command = inputLine[inputStart];

  if (command == '\0') {
    return '\0';
  }

  int inputEnd = inputStart + 1;

  while (inputLine[inputEnd] == ' ' || inputLine[inputEnd] == '\t') {
    inputEnd++;
  }

  // One-character commands only.
  if (inputLine[inputEnd] != '\0') {
    return '\0';
  }

  if (command >= 'A' && command <= 'Z') {
    command = command + 32;
  }

  return command;
}

void printReceivedInput(const char inputLine[]) {
  Serial.print("Serial Monitor input received: [");
  Serial.print(inputLine);
  Serial.println("]");
}

// ---------------------------------------------------------------------------
// Laser Command Handler
// ---------------------------------------------------------------------------

bool handleLaserCommand(char command) {
  if (command == '\0') {
    Serial.println("Wrong Format");
    Serial.println("Commands are one character only.");

    if (laserFiring) {
      Serial.println("Invalid input received while firing. Emergency stop triggered.");
      stopLaserAndRelock();
      Serial.println("All laser outputs are OFF. Laser commands are locked.");
    } else {
      printLaserCommandHelp();
    }

    return false;
  }

  Serial.print("Laser command input: ");
  Serial.println(command);

  // -------------------------------------------------------------------------
  // e: enable software command sequence
  // -------------------------------------------------------------------------
  if (command == 'e') {
    if (laserFiring) {
      Serial.println("Enable [e] is not allowed while firing. Emergency stop triggered.");
      stopLaserAndRelock();
      Serial.println("All laser outputs are OFF. Laser commands are locked.");
      return true;
    }

    if (laserEnabled) {
      Serial.println("Enable [e] ignored: laser commands are already unlocked.");
      return true;
    }

    driveLaserOutputsToReleasedState();
    laserEnabled = true;
    laserReady = false;

    Serial.println("Laser command: Enable [e]");
    Serial.println("Laser commands are unlocked. Next type Ready [r] before Fire [f].");
    return true;
  }

  // -------------------------------------------------------------------------
  // r: ready - open->settle->close edge, then hold
  // -------------------------------------------------------------------------
  if (command == 'r') {
    if (laserFiring) {
      Serial.println("Ready [r] is not allowed while firing. Emergency stop triggered.");
      stopLaserAndRelock();
      Serial.println("All laser outputs are OFF. Laser commands are locked.");
      return true;
    }

    if (!laserEnabled) {
      Serial.println("Ready blocked: type Enable [e] first.");
      printLaserCommandHelp();
      return true;
    }

    if (laserReady) {
      Serial.println("Ready [r] ignored: laser is already ready.");
      return true;
    }

    // Park the fire channels only - closeReadyContactWithEdge() owns pin 8.
    // The fire contacts must be provably at idle before the machine arms, or
    // it may latch a footswitch complaint at the moment it enters READY.
    pauseLaserFiring();

    Serial.println("Laser command: Ready [r]");
    closeReadyContactWithEdge();
    laserReady = true;

    // This flag is SOFTWARE STATE ONLY. Nothing here reads back from the
    // Dornier, so this sketch cannot know whether the machine actually armed.
    // Say so, rather than printing a confident "READY" that has repeatedly
    // been believed over the machine's own screen.
    Serial.println("Software now believes the laser is ready - this is NOT confirmation.");
    Serial.println(">>> LOOK AT THE DORNIER SCREEN. Does it read READY? <<<");
    return true;
  }

  // -------------------------------------------------------------------------
  // f: fire
  // -------------------------------------------------------------------------
  if (command == 'f') {
    if (!laserEnabled || !laserReady) {
      Serial.println("Fire blocked: type Enable [e], then Ready [r], then Fire [f].");
      printLaserCommandHelp();
      return true;
    }

    if (laserFiring) {
      Serial.println("Fire [f] ignored: laser is already firing.");
      return true;
    }

    if (!fireCh1Enabled && !fireCh2Enabled) {
      Serial.println("Fire blocked: both fire channels are disabled. Send [1] or [2].");
      return true;
    }

    Serial.println("Laser command: Fire [f]");
    printFireConfig();

    // Give the machine a clean, provably-idle footswitch window before
    // asserting. Both dwells are no-ops once enough time has already passed.
    waitForDwell(readyAssertedAtMs, FIRE_ARM_DWELL_MS, "post-arm");
    waitForDwell(fireIdleAtMs, FIRE_RELEASE_DWELL_MS, "post-release");

    assertFireChannels();
    laserFiring = true;

    Serial.println("Fire channels asserted and HELD. Send Pause [p] to release.");
    Serial.println("Still says \"release footswitch fully\"? Send [p], then try the");
    Serial.println("next row of the test matrix printed at boot.");
    return true;
  }

  // -------------------------------------------------------------------------
  // p: pause firing
  // -------------------------------------------------------------------------
  if (command == 'p') {
    Serial.println("Laser command: Pause [p]");
    pauseLaserFiring();
    Serial.println("Both fire channels are back at idle. Laser remains enabled and ready.");
    return true;
  }

  // -------------------------------------------------------------------------
  // s: standby - opens the ready contact
  // -------------------------------------------------------------------------
  if (command == 's') {
    if (!laserEnabled) {
      Serial.println("Standby blocked: type Enable [e] first.");
      printLaserCommandHelp();
      return true;
    }

    Serial.println("Laser command: Standby [s]");
    pauseLaserFiring();

    // Always drive the contact open, even if the software did not think the
    // laser was ready. If the two disagree, the safe move is to open.
    openReadyContact();

    laserReady = false;
    Serial.println("Standby finished. Type Ready [r] before Fire [f].");
    return true;
  }

  // -------------------------------------------------------------------------
  // x: stop and relock
  // -------------------------------------------------------------------------
  if (command == 'x') {
    Serial.println("Laser command: Stop [x]");
    stopLaserAndRelock();
    Serial.println("All outputs at idle. Ready contact is OPEN. Commands locked.");
    return true;
  }

  // -------------------------------------------------------------------------
  // 1 / 2: enable or disable a fire channel
  // -------------------------------------------------------------------------
  if (command == '1' || command == '2') {
    if (laserFiring) {
      Serial.println("Channel toggle refused while firing. Send Pause [p] first.");
      return true;
    }

    if (command == '1') {
      fireCh1Enabled = !fireCh1Enabled;
    } else {
      fireCh2Enabled = !fireCh2Enabled;
    }

    pauseLaserFiring();
    printFireConfig();
    return true;
  }

  // -------------------------------------------------------------------------
  // 3 / 4: invert a fire channel's polarity (changeover-pedal hypothesis)
  // -------------------------------------------------------------------------
  if (command == '3' || command == '4') {
    if (laserFiring) {
      Serial.println("Polarity toggle refused while firing. Send Pause [p] first.");
      return true;
    }

    if (command == '3') {
      fireCh1Invert = !fireCh1Invert;
    } else {
      fireCh2Invert = !fireCh2Invert;
    }

    // Re-park both channels under the NEW polarity, so idle really is idle.
    pauseLaserFiring();

    Serial.println("Channel polarity changed. Both channels re-parked at idle.");
    if (fireCh1Invert || fireCh2Invert) {
      Serial.println("NOTE: an inverted channel is ENERGIZED at idle. If the Dornier");
      Serial.println("starts complaining continuously with no Fire sent, that is this.");
    }
    printFireConfig();
    return true;
  }

  // -------------------------------------------------------------------------
  // o: swap which channel leads
  // -------------------------------------------------------------------------
  if (command == 'o') {
    if (laserFiring) {
      Serial.println("Lead swap refused while firing. Send Pause [p] first.");
      return true;
    }

    fireLeadChannel = (fireLeadChannel == 1) ? 2 : 1;
    printFireConfig();
    return true;
  }

  // -------------------------------------------------------------------------
  // g: step the inter-channel gap
  // -------------------------------------------------------------------------
  if (command == 'g') {
    fireGapIndex = (fireGapIndex + 1) % GAP_TABLE_COUNT;
    Serial.print("Inter-channel gap: ");
    Serial.print(fireGap_ms());
    Serial.println(" ms");
    return true;
  }

  // -------------------------------------------------------------------------
  // t / y: exercise one fire relay in isolation
  // -------------------------------------------------------------------------
  if (command == 't' || command == 'y') {
    if (laserFiring) {
      Serial.println("Bench test refused while firing. Send Pause [p] first.");
      return true;
    }

    if (command == 't') {
      exerciseFireRelay(fire1_laser, 1);
    } else {
      exerciseFireRelay(fire2_laser, 2);
    }

    return true;
  }

  // -------------------------------------------------------------------------
  // ?: status
  // -------------------------------------------------------------------------
  if (command == '?') {
    printBuildBanner();
    printMenu();
    printReadyWiring();
    printFireConfig();
    printLaserStatus();
    return true;
  }

  // -------------------------------------------------------------------------
  // Unknown command
  // -------------------------------------------------------------------------
  Serial.println("Unknown command.");

  if (laserFiring) {
    Serial.println("Unknown command received while firing. Emergency stop triggered.");
    stopLaserAndRelock();
    Serial.println("All laser outputs are OFF. Laser commands are locked.");
    return false;
  }

  printLaserCommandHelp();
  return false;
}

// ---------------------------------------------------------------------------
// Serial Printing
// ---------------------------------------------------------------------------

void printBuildBanner() {
  Serial.println("===========================================================");
  Serial.print("  BUILD: ");
  Serial.println(BUILD_NAME);
  Serial.print("  ");
  Serial.println(BUILD_NOTE);
  Serial.println("  No banner after a reset = the board is running a DIFFERENT");
  Serial.println("  sketch, and no test result from it means anything.");
  Serial.println("===========================================================");
}

void printMenu() {
  Serial.println("--- DORNIER LASER ACTIVATION SYSTEM ---");
  printLaserCommandHelp();
  Serial.println("---------------------------------------");
}

void printLaserCommandHelp() {
  Serial.println("LASER: [e] Enable | [r] Ready | [f] Fire | [p] Pause | [s] Standby | [x] Stop");
  Serial.println("FIRE:  [1]/[2] channel on-off | [3]/[4] invert polarity");
  Serial.println("       [o] swap lead | [g] gap ms | [?] status");
  Serial.println("BENCH: [t] exercise pin 9 relay | [y] exercise pin 10 relay");
}

void printReadyWiring() {
  Serial.println("  --- ready channel (pin 8) ---");
  Serial.print("  landed on     : ");
  Serial.println(READY_ON_NC ? "NC (contact CLOSED when coil released)"
                             : "NO (contact OPEN when coil released)");
  Serial.print("  close contact : pin 8 -> ");
  Serial.println(readyClosedLevel() == HIGH ? "HIGH" : "LOW");
  Serial.print("  open contact  : pin 8 -> ");
  Serial.println(readyOpenLevel() == HIGH ? "HIGH" : "LOW");
  Serial.println("  -----------------------------");
}

void printFireConfig() {
  Serial.println("  --- fire channels ---");
  Serial.print("  ch1 (pin 9)  : ");
  Serial.print(fireCh1Enabled ? "ENABLED " : "disabled");
  Serial.print(fireCh1Invert ? "  INVERTED (closed at idle, opens on fire)"
                             : "  normal (open at idle, closes on fire)");
  Serial.println();
  Serial.print("  ch2 (pin 10) : ");
  Serial.print(fireCh2Enabled ? "ENABLED " : "disabled");
  Serial.print(fireCh2Invert ? "  INVERTED (closed at idle, opens on fire)"
                             : "  normal (open at idle, closes on fire)");
  Serial.println();
  Serial.print("  leads        : channel ");
  Serial.println(fireLeadChannel);
  Serial.print("  gap          : ");
  Serial.print(fireGap_ms());
  Serial.println(" ms");
  Serial.println("  ---------------------");
}

void printLaserStatus() {
  Serial.print("Laser enabled/ready/firing: ");
  Serial.print(laserEnabled);
  Serial.print("/");
  Serial.print(laserReady);
  Serial.print("/");
  Serial.println(laserFiring);

  Serial.print("Pin levels 8/9/10: ");
  Serial.print(digitalRead(relay_laser));
  Serial.print("/");
  Serial.print(digitalRead(fire1_laser));
  Serial.print("/");
  Serial.println(digitalRead(fire2_laser));
}

// ---------------------------------------------------------------------------
// Arduino Setup
// ---------------------------------------------------------------------------

void laserSetup() {
  setupLaserOutputs();

  Serial.begin(115200);
  Serial.setTimeout(500);
  delay(2000);

  printBuildBanner();
  printMenu();
  printReadyWiring();
  printFireConfig();

  if (READY_ON_NC) {
    Serial.println("!! FAIL-SAFE WARNING: pin 8 is on the relay's NC terminal.");
    Serial.println("!! Standby needs the coil ENERGIZED, so a reset, replug, upload,");
    Serial.println("!! loose jumper, or relay-supply loss ARMS the laser unattended.");
    Serial.println("!! Fix in hardware: move pin 8 from NC to NO, then set");
    Serial.println("!! READY_ON_NC = false. Do not leave this rig unattended.");
  } else {
    Serial.println("Fail-safe: pin 8 treated as NO. Coil released = contact open =");
    Serial.println("standby, so a reset or power loss drops the laser to standby.");
    Serial.println("This is the correct and safe configuration.");
  }

  Serial.println("STATUS: Fire is working. Ready is the open item.");
  Serial.println("  Ready does not arm? Send [w] to flip the pin 8 sense at");
  Serial.println("  runtime, then [x] [e] [r] and watch the Dornier screen.");
  Serial.println("  [w] is runtime only - it resets on every boot. Tell me which");
  Serial.println("  way works and I will make it the permanent default.");
  printLaserStatus();
}

// ---------------------------------------------------------------------------
// Arduino Main Loop
// ---------------------------------------------------------------------------



// ==========================================================================
// Motion velocity server
// ==========================================================================


#include <SCServo.h>
#include <math.h>
#include <stdint.h>
#include <stdlib.h>

SMS_STS servo;

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

const int linear_enaPin = 2;
const int linear_dirPin = 3;
const int linear_stepPin = 4;

const int rotation_enaPin = 5;
const int rotation_dirPin = 6;
const int rotation_stepPin = 7;


const int enaPin_Enable = LOW;
const int enaPin_Disable = HIGH;

// Direction levels, carried over from 3DOF_MovementF.ino.
const int linear_dirForward = LOW;
const int linear_dirBackward = HIGH;
const int rotation_dirClockwise = HIGH;
const int rotation_dirCounter = LOW;

// ---------------------------------------------------------------------------
// Axis calibration
// ---------------------------------------------------------------------------

const float linearMMPerRev = 4.0f;          // TR8x4 lead screw
const float linearPulsesPerRev = 1600.0f;   // match the TB6600 microstep DIPs
const float linearStepsPerMM = linearPulsesPerRev / linearMMPerRev;

const float linearMinPositionMM = 0.0f;
const float linearMaxPositionMM = 177.0f;
const float linearLimitToleranceMM = 0.01f;

const float rotationPulsesPerRev = 1600.0f;
const float rotationGearRatio = 2.5f;       // motor deg per ureteroscope deg
const float rotationStepsPerScopeDeg =
  (rotationPulsesPerRev / 360.0f) * rotationGearRatio;

// Ceilings. The host clamps too, but these are the backstop.
const float linearMaxSpeedMMPerSec = 12.0f;
const float rotationMaxSpeedDegPerSec = 120.0f;

// Ramp rates. These are what make motion smooth: the motor is never commanded
// to jump to speed, so it does not stall or cog on starting.
const float linearAccelMMPerSec2 = 40.0f;
const float linearDecelMMPerSec2 = 80.0f;
const float rotationAccelDegPerSec2 = 400.0f;
const float rotationDecelDegPerSec2 = 800.0f;

const float stoppedLinearTolerance = 0.002f;
const float stoppedRotationTolerance = 0.02f;

const unsigned int stepPulseHighTime_us = 5;
const unsigned int directionSetupTime_us = 20;

// Ramp to a stop if the host goes quiet.
const unsigned long commandTimeout_ms = 400;

// ---------------------------------------------------------------------------
// Flexion (ST3020)
// ---------------------------------------------------------------------------

const long servo_baud = 1000000;
const int servo_ID = 1;
// Servo speed is NOT a constant any more, and that is the whole reason flexion
// used to stutter.
//
// WritePosEx takes a speed in servo steps/s. A fixed high value means the servo
// sprints to whatever target it was last given, arrives, and stops dead until
// the next one -- so jogging came out as a string of little lunges no matter
// how the deadband was tuned. At 8 tip deg/s the tip actually needs about
//   (8 / 1.714) / 360 * 4095  ~=  53 steps/s
// against the 900 it was being told. Seventeen times too fast.
//
// applyFlexionTarget() now measures how fast the host's target is moving and
// sets the servo speed to match, so the servo travels continuously instead of
// arriving early and waiting.
const int servo_acceleration = 60;
// Pinned to a flat 53 steps/s for now (the speed needed at the usual 8
// tip-deg/s jog rate) instead of matching the live target rate.
const int flexionMinServoSpeed = 53;
const int flexionMaxServoSpeed = 53;

// Command the servo a little AHEAD of the target so it always has somewhere to
// travel to. Without this it converges on the current target and stops between
// updates, which is the same stutter by another route.
float flexionLeadSeconds = 0.35f;

// Low-pass on the measured target velocity. The host's updates are quantised by
// its own deadband, so the raw difference is lumpy.
const float flexionVelocityFilter = 0.35f;

float flexionTargetVelocityDegPerSec = 0.0f;
float flexionPrevTargetDeg = 0.0f;
unsigned long flexionLastApply_ms = 0;
int flexionLastSentStep = -1;
const unsigned long flexionApplyInterval_ms = 20;
const int flexionNeutralStep = 2048;
const int servoMaximumStep = 4095;

const float flexionGearRatio = 3.5f;
const float flexionTwistFactor0To90 = 6.0f;
const float flexionTwistFactor90To180 = 6.5f;
const float flexionTwistFactor180To270 = 7.2f;
const float flexionMaxTipDeg = 270.0f;
const float flexionMinTipDeg = -270.0f;

// Only re-command the servo once the target has moved this far.
//
// This has to be sized against the flexion RATE, not picked once. At 30 deg/s a
// 3 deg deadband means a new target every 100 ms, which reads as continuous. At
// 8 deg/s the same deadband is one 3 deg hop every 375 ms -- visibly steppy.
// Small enough that commands stay frequent at the slowest usable rate, but not
// so small that the servo is re-commanded faster than it can act on.
// Runtime-settable with [D<deg>] so it can be tuned against the feel of the rig
// rather than guessed at.
float flexionCommandDeadbandDeg = 0.25f;

bool servoConnected = false;
float flexionTargetTipDeg = 0.0f;
float flexionLastSentTipDeg = 0.0f;

// ---------------------------------------------------------------------------
// Motion state
// ---------------------------------------------------------------------------

float targetLinearSpeed = 0.0f;
float currentLinearSpeed = 0.0f;
float linearPositionMM = 0.0f;
long linearStepEstimate = 0;

float targetRotationSpeed = 0.0f;
float currentRotationSpeed = 0.0f;
float rotationPositionDeg = 0.0f;
long rotationStepEstimate = 0;

bool linearPulseHigh = false;
bool rotationPulseHigh = false;
int linearActiveDir = 0;
int rotationActiveDir = 0;
unsigned long linearPulseHighStart_us = 0;
unsigned long rotationPulseHighStart_us = 0;
unsigned long linearLastRise_us = 0;
unsigned long rotationLastRise_us = 0;
unsigned long linearDirChanged_us = 0;
unsigned long rotationDirChanged_us = 0;
unsigned long lastVelocityUpdate_us = 0;

unsigned long lastCommand_ms = 0;
bool watchdogTripped = false;
unsigned long telemetryPeriod_ms = 100;
unsigned long lastTelemetry_ms = 0;

bool homing = false;
const float homeApproachGain = 1.2f;
const float homeLinearToleranceMM = 0.05f;
const float homeRotationToleranceDeg = 0.5f;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

float clampf(float v, float lo, float hi) {
  if (v < lo) return lo;
  if (v > hi) return hi;
  return v;
}

float rampToward(float current, float target, float maxChange) {
  if (current < target) {
    current += maxChange;
    if (current > target) current = target;
  } else if (current > target) {
    current -= maxChange;
    if (current < target) current = target;
  }
  return current;
}

float chooseRamp(float current, float target, float accel, float decel) {
  bool sameDirection = (current >= 0.0f && target >= 0.0f) ||
                       (current <= 0.0f && target <= 0.0f);
  if (sameDirection && fabsf(target) > fabsf(current)) {
    return accel;
  }
  return decel;
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------





// Assert the enabled channels in the configured order, with the configured gap.
// "Asserted" respects each channel's polarity, so an inverted channel OPENS
// here while a normal one CLOSES.


// Bench test one fire relay alone. The ready contact is forced OPEN for the
// whole test, so the machine is in standby and nothing can fire whatever these
// contacts do. Listen for the click, meter the output terminals.






void setupSteppers() {
  pinMode(linear_stepPin, OUTPUT);
  pinMode(linear_dirPin, OUTPUT);
  pinMode(linear_enaPin, OUTPUT);
  pinMode(rotation_stepPin, OUTPUT);
  pinMode(rotation_dirPin, OUTPUT);
  pinMode(rotation_enaPin, OUTPUT);

  digitalWrite(linear_stepPin, LOW);
  digitalWrite(rotation_stepPin, LOW);
  digitalWrite(linear_dirPin, linear_dirForward);
  digitalWrite(rotation_dirPin, rotation_dirClockwise);
  digitalWrite(linear_enaPin, enaPin_Enable);
  digitalWrite(rotation_enaPin, enaPin_Enable);
}

void setupFlexion() {
  Serial1.begin(servo_baud);
  servo.pSerial = &Serial1;
  servoConnected = (servo.Ping(servo_ID) != -1);
  if (servoConnected) {
    servo.EnableTorque(servo_ID, 1);
    // One-off move to neutral at startup, so a fixed moderate speed is right
    // here -- the rate matching below only applies to jogging.
    servo.WritePosEx(servo_ID, flexionNeutralStep, 400, servo_acceleration);
  }
}

void setup() {
  setupLaserOutputs();   // relays to a safe state first, always
  setupSteppers();
  Serial.begin(115200);
  Serial.setTimeout(50);
  setupFlexion();

  lastVelocityUpdate_us = micros();
  lastCommand_ms = millis();

  Serial.println();
  Serial.println("=== MOTION VELOCITY SERVER  BUILD VEL-1 ===");
  Serial.print("Flexion servo: ");
  Serial.println(servoConnected ? "connected" : "NOT FOUND");
  Serial.println("L<mm/s> R<deg/s> F<deg> S Z H T<ms> ?   plus laser e r f p s x");
  Serial.println("Carriage start position is treated as 0.00 mm.");
  if (READY_ON_NC) {
    Serial.println("!! pin 8 on NC: de-energised coil = ARMED.");
    Serial.println("!! De-energise the relay supply before flashing.");
  }
}

// ---------------------------------------------------------------------------
// Velocity and pulse generation
// ---------------------------------------------------------------------------

void updateVelocities() {
  unsigned long now_us = micros();
  float dt = (float)(now_us - lastVelocityUpdate_us) / 1000000.0f;
  lastVelocityUpdate_us = now_us;

  if (dt <= 0.0f || dt > 0.25f) {
    return;
  }

  currentLinearSpeed = rampToward(
    currentLinearSpeed, targetLinearSpeed,
    chooseRamp(currentLinearSpeed, targetLinearSpeed,
               linearAccelMMPerSec2, linearDecelMMPerSec2) * dt);

  currentRotationSpeed = rampToward(
    currentRotationSpeed, targetRotationSpeed,
    chooseRamp(currentRotationSpeed, targetRotationSpeed,
               rotationAccelDegPerSec2, rotationDecelDegPerSec2) * dt);

  if (fabsf(currentLinearSpeed) < stoppedLinearTolerance &&
      fabsf(targetLinearSpeed) < stoppedLinearTolerance) {
    currentLinearSpeed = 0.0f;
  }
  if (fabsf(currentRotationSpeed) < stoppedRotationTolerance &&
      fabsf(targetRotationSpeed) < stoppedRotationTolerance) {
    currentRotationSpeed = 0.0f;
  }
}

bool linearWouldExceedLimit(float speed) {
  if (speed < 0.0f && linearPositionMM <= linearMinPositionMM + linearLimitToleranceMM) return true;
  if (speed > 0.0f && linearPositionMM >= linearMaxPositionMM - linearLimitToleranceMM) return true;
  return false;
}

void pulseLinear() {
  unsigned long now_us = micros();

  if (linearPulseHigh && now_us - linearPulseHighStart_us >= stepPulseHighTime_us) {
    digitalWrite(linear_stepPin, LOW);
    linearPulseHigh = false;
  }
  if (linearPulseHigh || fabsf(currentLinearSpeed) < stoppedLinearTolerance) {
    return;
  }
  if (linearWouldExceedLimit(currentLinearSpeed)) {
    currentLinearSpeed = 0.0f;
    targetLinearSpeed = 0.0f;
    return;
  }

  int dir = currentLinearSpeed > 0.0f ? +1 : -1;
  if (dir != linearActiveDir) {
    linearActiveDir = dir;
    digitalWrite(linear_dirPin, dir > 0 ? linear_dirForward : linear_dirBackward);
    linearDirChanged_us = now_us;
    return;
  }
  if (now_us - linearDirChanged_us < directionSetupTime_us) {
    return;
  }

  float stepRate = fabsf(currentLinearSpeed) * linearStepsPerMM;
  if (stepRate <= 0.0f) return;
  unsigned long interval_us = (unsigned long)(1000000.0f / stepRate);
  if (interval_us < stepPulseHighTime_us + 2) interval_us = stepPulseHighTime_us + 2;

  if (linearLastRise_us == 0 || now_us - linearLastRise_us >= interval_us) {
    digitalWrite(linear_stepPin, HIGH);
    linearPulseHigh = true;
    linearPulseHighStart_us = now_us;
    linearLastRise_us = now_us;

    linearStepEstimate += dir;
    linearPositionMM = (float)linearStepEstimate / linearStepsPerMM;
    linearPositionMM = clampf(linearPositionMM, linearMinPositionMM, linearMaxPositionMM);
  }
}

void pulseRotation() {
  unsigned long now_us = micros();

  if (rotationPulseHigh && now_us - rotationPulseHighStart_us >= stepPulseHighTime_us) {
    digitalWrite(rotation_stepPin, LOW);
    rotationPulseHigh = false;
  }
  if (rotationPulseHigh || fabsf(currentRotationSpeed) < stoppedRotationTolerance) {
    return;
  }

  int dir = currentRotationSpeed > 0.0f ? +1 : -1;
  if (dir != rotationActiveDir) {
    rotationActiveDir = dir;
    digitalWrite(rotation_dirPin, dir > 0 ? rotation_dirClockwise : rotation_dirCounter);
    rotationDirChanged_us = now_us;
    return;
  }
  if (now_us - rotationDirChanged_us < directionSetupTime_us) {
    return;
  }

  float stepRate = fabsf(currentRotationSpeed) * rotationStepsPerScopeDeg;
  if (stepRate <= 0.0f) return;
  unsigned long interval_us = (unsigned long)(1000000.0f / stepRate);
  if (interval_us < stepPulseHighTime_us + 2) interval_us = stepPulseHighTime_us + 2;

  if (rotationLastRise_us == 0 || now_us - rotationLastRise_us >= interval_us) {
    digitalWrite(rotation_stepPin, HIGH);
    rotationPulseHigh = true;
    rotationPulseHighStart_us = now_us;
    rotationLastRise_us = now_us;

    rotationStepEstimate += dir;
    rotationPositionDeg = (float)rotationStepEstimate / rotationStepsPerScopeDeg;
  }
}

void stopMotion() {
  targetLinearSpeed = 0.0f;
  targetRotationSpeed = 0.0f;
  currentLinearSpeed = 0.0f;
  currentRotationSpeed = 0.0f;
  digitalWrite(linear_stepPin, LOW);
  digitalWrite(rotation_stepPin, LOW);
  linearPulseHigh = false;
  rotationPulseHigh = false;
  homing = false;
}

// ---------------------------------------------------------------------------
// Flexion
// ---------------------------------------------------------------------------

float flexionTipGain(float tipDeg) {
  float a = fabsf(tipDeg);
  float twist = (a <= 90.0f)  ? flexionTwistFactor0To90
              : (a <= 180.0f) ? flexionTwistFactor90To180
                              : flexionTwistFactor180To270;
  return twist / flexionGearRatio;
}

void applyFlexionTarget() {
  if (!servoConnected) return;

  unsigned long now = millis();
  if (now - flexionLastApply_ms < flexionApplyInterval_ms) return;

  float dt = (float)(now - flexionLastApply_ms) / 1000.0f;
  flexionLastApply_ms = now;
  if (dt <= 0.0f || dt > 0.5f) {
    flexionPrevTargetDeg = flexionTargetTipDeg;
    return;
  }

  // How fast the host is sweeping the target. This is what the servo speed has
  // to match for the motion to come out continuous.
  float rawVelocity = (flexionTargetTipDeg - flexionPrevTargetDeg) / dt;
  flexionPrevTargetDeg = flexionTargetTipDeg;
  flexionTargetVelocityDegPerSec =
    (1.0f - flexionVelocityFilter) * flexionTargetVelocityDegPerSec +
    flexionVelocityFilter * rawVelocity;

  float gain = flexionTipGain(flexionTargetTipDeg);

  // Aim ahead of the target while moving so the servo never converges and
  // stalls between updates. Standing still, lead collapses to zero.
  float commandTipDeg =
    flexionTargetTipDeg + flexionTargetVelocityDegPerSec * flexionLeadSeconds;
  commandTipDeg = clampf(commandTipDeg, flexionMinTipDeg, flexionMaxTipDeg);

  float motorDeg = commandTipDeg / gain;
  if (motorDeg < -180.0f || motorDeg > 180.0f) return;
  int steps = (int)lroundf(((motorDeg + 180.0f) * servoMaximumStep) / 360.0f);

  // Speed matched to the commanded tip rate, in servo steps per second.
  float motorDegPerSec = fabsf(flexionTargetVelocityDegPerSec) / gain;
  int speed = (int)lroundf((motorDegPerSec / 360.0f) * (float)servoMaximumStep);
  speed = (int)clampf((float)speed, (float)flexionMinServoSpeed,
                      (float)flexionMaxServoSpeed);

  // Nothing to say: same step, and not moving.
  bool idle = fabsf(flexionTargetVelocityDegPerSec) < 0.05f;
  if (steps == flexionLastSentStep && idle) return;

  // While idle, respect the deadband so a resting stick does not trickle
  // commands at the servo.
  if (idle && fabsf(flexionTargetTipDeg - flexionLastSentTipDeg) < flexionCommandDeadbandDeg) {
    return;
  }

  servo.WritePosEx(servo_ID, steps, speed, servo_acceleration);
  flexionLastSentStep = steps;
  flexionLastSentTipDeg = flexionTargetTipDeg;
}

// ---------------------------------------------------------------------------
// Homing  (non-blocking: it just steers the velocity targets)
// ---------------------------------------------------------------------------

void updateHoming() {
  if (!homing) return;

  float linearError = -linearPositionMM;
  float rotationError = -rotationPositionDeg;

  bool linearThere = fabsf(linearError) <= homeLinearToleranceMM;
  bool rotationThere = fabsf(rotationError) <= homeRotationToleranceDeg;

  flexionTargetTipDeg = 0.0f;

  if (linearThere && rotationThere) {
    homing = false;
    stopMotion();
    Serial.println("HOME complete");
    return;
  }

  targetLinearSpeed = linearThere ? 0.0f
    : clampf(linearError * homeApproachGain, -linearMaxSpeedMMPerSec, linearMaxSpeedMMPerSec);
  targetRotationSpeed = rotationThere ? 0.0f
    : clampf(rotationError * homeApproachGain * 10.0f,
             -rotationMaxSpeedDegPerSec, rotationMaxSpeedDegPerSec);
}

// ---------------------------------------------------------------------------
// Laser commands
// ---------------------------------------------------------------------------





// ---------------------------------------------------------------------------
// Command parsing
// ---------------------------------------------------------------------------

void emitTelemetry() {
  Serial.print("TEL L");
  Serial.print(linearPositionMM, 3);
  Serial.print(" R");
  Serial.print(rotationPositionDeg, 2);
  Serial.print(" F");
  Serial.print(flexionTargetTipDeg, 2);
  Serial.print(" VL");
  Serial.print(currentLinearSpeed, 3);
  Serial.print(" VR");
  Serial.print(currentRotationSpeed, 2);
  Serial.print(" E");
  Serial.print(laserEnabled ? 1 : 0);
  Serial.print(" Y");
  Serial.print(laserReady ? 1 : 0);
  Serial.print(" G");
  Serial.print(laserFiring ? 1 : 0);
  Serial.print(" H");
  Serial.println(homing ? 1 : 0);
}

void handleLine(char *line) {
  lastCommand_ms = millis();

  // Trim leading space.
  while (*line == ' ' || *line == '\t') line++;
  if (*line == '\0') return;

  char c = *line;

  // Length is checked BEFORE dispatching. Written the other way round, the
  // handleLaserCommand() call sits earlier in the && chain and therefore RUNS
  // -- side effects and all -- for any multi-character line that happens to
  // begin with a laser letter. A stray "s..." or "f..." would have fired or
  // stood the machine down as a side effect of parsing.
  if (line[1] == '\0' && c >= 'a' && c <= 'z' && handleLaserCommand(c)) {
    printLaserStatus();
    return;
  }
  if (c >= '1' && c <= '4' && line[1] == '\0') {
    handleLaserCommand(c);
    printLaserStatus();
    return;
  }

  switch (c) {
    case 'L': case 'l':
      homing = false;
      targetLinearSpeed = clampf(atof(line + 1), -linearMaxSpeedMMPerSec, linearMaxSpeedMMPerSec);
      return;

    case 'R':
      homing = false;
      targetRotationSpeed = clampf(atof(line + 1), -rotationMaxSpeedDegPerSec, rotationMaxSpeedDegPerSec);
      return;

    case 'F':
      flexionTargetTipDeg = clampf(atof(line + 1), flexionMinTipDeg, flexionMaxTipDeg);
      return;

    case 'S':
      stopMotion();
      Serial.println("STOPPED");
      return;

    case 'Z':
      linearStepEstimate = 0;
      rotationStepEstimate = 0;
      linearPositionMM = 0.0f;
      rotationPositionDeg = 0.0f;
      Serial.println("ZEROED");
      return;

    case 'H':
      homing = true;
      Serial.println("HOMING");
      return;

    case 'P': {
      // Fire-channel polarity as an absolute mask, bit0 = ch1, bit1 = ch2.
      // The 3/4 toggles are fine by hand but useless from a host: they flip
      // relative to whatever state the board happens to be in, so reconnecting
      // without a reboot inverts the wrong way. This is idempotent.
      int mask = atoi(line + 1);
      fireCh1Invert = (mask & 1) != 0;
      fireCh2Invert = (mask & 2) != 0;
      driveFireChannelsToIdle();
      Serial.print("Fire polarity: ch1 ");
      Serial.print(fireCh1Invert ? "INVERTED" : "normal");
      Serial.print(", ch2 ");
      Serial.println(fireCh2Invert ? "INVERTED" : "normal");
      return;
    }

    case 'A':
      flexionLeadSeconds = clampf(atof(line + 1), 0.0f, 2.0f);
      Serial.print("Flexion lead ");
      Serial.print(flexionLeadSeconds, 3);
      Serial.println(" s");
      return;

    case 'D':
      flexionCommandDeadbandDeg = clampf(atof(line + 1), 0.02f, 10.0f);
      Serial.print("Flexion deadband ");
      Serial.print(flexionCommandDeadbandDeg, 2);
      Serial.println(" deg");
      return;

    case 'T':
      telemetryPeriod_ms = (unsigned long)atol(line + 1);
      Serial.print("Telemetry period ");
      Serial.println(telemetryPeriod_ms);
      return;

    case '?':
      emitTelemetry();
      printLaserStatus();
      return;

    default:
      Serial.print("Unknown command: ");
      Serial.println(line);
      return;
  }
}

void readSerial() {
  static char buffer[48];
  static uint8_t length = 0;

  while (Serial.available() > 0) {
    char c = (char)Serial.read();
    if (c == '\n' || c == '\r') {
      if (length > 0) {
        buffer[length] = '\0';
        handleLine(buffer);
        length = 0;
      }
      continue;
    }
    if (length < sizeof(buffer) - 1) {
      buffer[length++] = c;
    }
  }
}

// ---------------------------------------------------------------------------
// Main loop  -  nothing in here blocks
// ---------------------------------------------------------------------------

void loop() {
  readSerial();

  // Host went quiet: ramp to a stop rather than run on at the last velocity.
  // Announced, not silent -- an unexplained stop mid-jog is indistinguishable
  // from a mechanical fault, and a host that stops sending because its command
  // did not change looks exactly like a host that died.
  if (millis() - lastCommand_ms > commandTimeout_ms) {
    if (!watchdogTripped &&
        (fabsf(targetLinearSpeed) > 0.0f || fabsf(targetRotationSpeed) > 0.0f)) {
      Serial.print("WATCHDOG: no command for ");
      Serial.print(millis() - lastCommand_ms);
      Serial.println(" ms, ramping to a stop");
      watchdogTripped = true;
    }
    targetLinearSpeed = 0.0f;
    targetRotationSpeed = 0.0f;
    homing = false;
  } else {
    watchdogTripped = false;
  }

  updateHoming();
  updateVelocities();
  pulseLinear();
  pulseRotation();
  applyFlexionTarget();

  if (telemetryPeriod_ms > 0 && millis() - lastTelemetry_ms >= telemetryPeriod_ms) {
    lastTelemetry_ms = millis();
    emitTelemetry();
  }
}
