#!/usr/bin/env python3
"""Generate Motion_Velocity_Server.ino: velocity motion core + the ORIGINAL laser code.

Why this exists
---------------
The velocity firmware was first written with the laser reimplemented by hand.
That reimplementation silently dropped nine things the original sketch had --
the arm and release dwell timers, the fire-channel lead order and gap, the
per-relay bench test, and the timestamps all of those depend on. The laser had
been working on Combined_Motion_Laser, which carries the original code verbatim,
and stopped working the moment the rewrite replaced it.

So the laser is no longer hand-maintained here. `firmware/src/velocity_motion_core.inc`
holds only the motion server; the laser half is spliced in from
shootingyesready_inoF-1.ino unchanged, exactly as build_merged_firmware.py does.
Safety-critical code that already worked should not be retyped.

    python scripts/build_velocity_firmware.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CORE = ROOT / "firmware" / "src" / "velocity_motion_core.inc"
LASER_SRC = ROOT / "firmware" / "original" / "shootingyesready_inoF-1" / "shootingyesready_inoF-1.ino"
OUT_DIR = ROOT / "firmware" / "Motion_Velocity_Server"
OUT_FILE = OUT_DIR / "Motion_Velocity_Server.ino"


def strip_function(source: str, signature: str, *, required: bool = True) -> str:
    """Remove one brace-balanced top-level function definition."""
    start = source.find(signature)
    if start == -1:
        if required:
            raise SystemExit(f"could not find {signature!r} to remove")
        return source

    brace = source.find("{", start)
    if brace == -1:
        raise SystemExit(f"no opening brace after {signature!r}")

    depth = 0
    for i in range(brace, len(source)):
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
            if depth == 0:
                return source[:start] + source[i + 1 :]
    raise SystemExit(f"unbalanced braces in {signature!r}")


def require(source: str, needle: str, label: str) -> None:
    if needle not in source:
        raise SystemExit(
            f"expected text not found in {label}: {needle!r}\n"
            "The source changed shape; update this build script."
        )


def transform_laser(source: str) -> str:
    """The original laser sketch, minus its own setup() and loop()."""
    require(source, "void setup() {", "laser sketch")
    source = source.replace("void setup() {", "void laserSetup() {", 1)
    source = strip_function(source, "void loop() {")
    source = re.sub(r"\A///[^\n]*\n/\*.*?\*/\n", "", source, count=1, flags=re.DOTALL)
    return source


HEADER = """/// Motion Velocity Server  -  Teensy 4.1  -  GENERATED FILE, DO NOT EDIT BY HAND
/*
  Generated by python/scripts/build_velocity_firmware.py from:
    firmware/src/velocity_motion_core.inc          (motion, hand-maintained)
    shootingyesready_inoF-1/shootingyesready_inoF-1.ino   (laser, VERBATIM)

  Edit those and re-run the build script. Editing this file means the next
  build discards your change.

  THE LASER CODE HERE IS NOT A REIMPLEMENTATION.
    An earlier version of this sketch rewrote the laser by hand and lost the arm
    and release dwell timers, the fire-channel lead order and gap, and the
    per-relay bench test. The laser worked before that rewrite and stopped
    afterwards. It is now spliced in from the original sketch unchanged, so its
    behaviour is identical to the build it was working on.

  MOTION
    Velocity mode: the host sets a target speed per axis and the firmware ramps
    toward it, stepping continuously. Nothing blocks, so motion is smooth,
    proportional to stick deflection, and stoppable inside a millisecond.
    Position is estimated by counting STEP pulses; the encoders are not read.
    Start the carriage at mechanical home -- that becomes 0.00 mm.

  COMMANDS
    L<mm/s>   target linear velocity        S    stop all motion now
    R<deg/s>  target rotation velocity      Z    zero the position estimates
    F<deg>    absolute flexion tip angle    H    home (abortable with S)
    T<ms>     telemetry period              D<deg> flexion re-command deadband
    A<sec>    flexion lead time             P<mask> fire polarity, bit0=ch1 bit1=ch2
    ?         status

    e r f p s x 1 2 3 4 o g t y w   laser, exactly as the original sketch

  !!! LASER FAIL-SAFE - LIVE !!!
    READY_ON_NC is true: pin 8 is on the relay's NC terminal, so the ready
    contact is CLOSED (laser ARMED) whenever the coil is de-energised. A reset,
    replug, upload, loose jumper or loss of relay supply arms the laser with
    nobody commanding it. De-energise the relay supply before flashing.
    Fix in hardware: move pin 8 to NO, then set READY_ON_NC = false.
*/

"""


def main() -> int:
    for path in (CORE, LASER_SRC):
        if not path.exists():
            raise SystemExit(f"source not found: {path}")

    core = CORE.read_text()
    laser = transform_laser(LASER_SRC.read_text())

    merged = (
        HEADER
        + "// " + "=" * 74 + "\n"
        + "// Laser, spliced verbatim from shootingyesready_inoF-1.ino\n"
        + "// " + "=" * 74 + "\n\n"
        + laser
        + "\n// " + "=" * 74 + "\n"
        + "// Motion velocity server\n"
        + "// " + "=" * 74 + "\n\n"
        + core
    )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(merged)

    # Every laser feature that the hand-rewrite lost must be present.
    for symbol in (
        "FIRE_ARM_DWELL_MS",
        "FIRE_RELEASE_DWELL_MS",
        "fireLeadChannel",
        "GAP_TABLE_MS",
        "exerciseFireRelay",
        "waitForDwell",
        "readyAssertedAtMs",
        "fireIdleAtMs",
        "assertFireChannels",
        "closeReadyContactWithEdge",
        "stopLaserAndRelock",
    ):
        if symbol not in merged:
            raise SystemExit(f"laser feature missing from the merge: {symbol}")

    if merged.count("\nvoid setup() {") != 1 or merged.count("\nvoid loop() {") != 1:
        raise SystemExit("merge produced the wrong number of setup()/loop() definitions")

    print(f"wrote {OUT_FILE}")
    print(f"  {len(merged.splitlines())} lines")
    print(f"  laser: {len(laser.splitlines())} lines, verbatim from {LASER_SRC.name}")
    print(f"  motion: {len(core.splitlines())} lines from {CORE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
